<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class AuditsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('audits')->delete();
        
        \DB::table('audits')->insert(array (
            0 => 
            array (
                'auditable_id' => 2,
                'auditable_type' => 'App\\Models\\Servicios',
                'created_at' => '2023-07-25 01:03:53',
                'deleted_at' => NULL,
                'event' => 'created',
                'id' => 1,
                'ip_address' => '127.0.0.1',
                'new_values' => '{"name":"Traumatolog\\u00eda","precio":"250","id":2}',
                'old_values' => '[]',
                'tags' => NULL,
                'updated_at' => '2023-07-31 21:59:35',
                'url' => 'https://sisaf.test/admin/servicios',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36',
                'user_id' => 2,
                'user_type' => 'App\\Models\\User',
            ),
            1 => 
            array (
                'auditable_id' => 2,
                'auditable_type' => 'App\\Models\\Materiales',
                'created_at' => '2023-08-03 00:40:16',
                'deleted_at' => NULL,
                'event' => 'updated',
                'id' => 2,
                'ip_address' => '127.0.0.1',
                'new_values' => '{"name":"Jeringas 1cc"}',
                'old_values' => '{"name":"Jeringas"}',
                'tags' => NULL,
                'updated_at' => '2023-08-03 00:40:16',
                'url' => 'https://sisaf.test/admin/materiales/2',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36',
                'user_id' => 2,
                'user_type' => 'App\\Models\\User',
            ),
            2 => 
            array (
                'auditable_id' => 1,
                'auditable_type' => 'App\\Models\\Materiales',
                'created_at' => '2023-08-11 21:18:22',
                'deleted_at' => NULL,
                'event' => 'deleted',
                'id' => 3,
                'ip_address' => '127.0.0.1',
                'new_values' => '[]',
                'old_values' => '{"id":1,"name":"Pinzas","descripcion":"Pinzas de disecci\\u00f3n o pinzas m\\u00e9dicas","costo":"20","cantidad":"2","costo_ultimo":"20"}',
                'tags' => NULL,
                'updated_at' => '2023-08-11 21:18:22',
                'url' => 'https://sisaf.test/admin/materiales/1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36',
                'user_id' => 2,
                'user_type' => 'App\\Models\\User',
            ),
            3 => 
            array (
                'auditable_id' => 1,
                'auditable_type' => 'App\\Models\\Materiales',
                'created_at' => '2023-08-11 21:23:24',
                'deleted_at' => NULL,
                'event' => 'restored',
                'id' => 4,
                'ip_address' => '127.0.0.1',
                'new_values' => '{"id":1,"name":"Pinzas","descripcion":"Pinzas de disecci\\u00f3n o pinzas m\\u00e9dicas","costo":"20","cantidad":"2","costo_ultimo":"20"}',
                'old_values' => '[]',
                'tags' => NULL,
                'updated_at' => '2023-08-11 21:23:24',
                'url' => 'https://sisaf.test/admin/materiales/1/restore',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36',
                'user_id' => 2,
                'user_type' => 'App\\Models\\User',
            ),
            4 => 
            array (
                'auditable_id' => 3,
                'auditable_type' => 'App\\Models\\Materiales',
                'created_at' => '2023-08-11 21:23:43',
                'deleted_at' => NULL,
                'event' => 'created',
                'id' => 5,
                'ip_address' => '127.0.0.1',
                'new_values' => '{"name":"prueba","descripcion":"Pinzas de disecci\\u00f3n o pinzas m\\u00e9dicas","costo":"20","cantidad":"123","costo_ultimo":"123","id":3}',
                'old_values' => '[]',
                'tags' => NULL,
                'updated_at' => '2023-08-11 21:23:43',
                'url' => 'https://sisaf.test/admin/materiales',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36',
                'user_id' => 2,
                'user_type' => 'App\\Models\\User',
            ),
            5 => 
            array (
                'auditable_id' => 3,
                'auditable_type' => 'App\\Models\\Materiales',
                'created_at' => '2023-08-11 21:23:51',
                'deleted_at' => NULL,
                'event' => 'deleted',
                'id' => 6,
                'ip_address' => '127.0.0.1',
                'new_values' => '[]',
                'old_values' => '{"id":3,"name":"prueba","descripcion":"Pinzas de disecci\\u00f3n o pinzas m\\u00e9dicas","costo":"20","cantidad":"123","costo_ultimo":"123"}',
                'tags' => NULL,
                'updated_at' => '2023-08-11 21:23:51',
                'url' => 'https://sisaf.test/admin/materiales/0',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36',
                'user_id' => 2,
                'user_type' => 'App\\Models\\User',
            ),
            6 => 
            array (
                'auditable_id' => 2,
                'auditable_type' => 'App\\Models\\Materiales',
                'created_at' => '2023-08-11 21:24:04',
                'deleted_at' => NULL,
                'event' => 'deleted',
                'id' => 7,
                'ip_address' => '127.0.0.1',
                'new_values' => '[]',
                'old_values' => '{"id":2,"name":"Jeringas 1cc","descripcion":"1 cc. o ml. Aguja de calibre de 27x5\\/8\\", Se coloca en 0\\u00ba - Para intrad\\u00e9rmicas","costo":"20","cantidad":"10","costo_ultimo":"20"}',
                'tags' => NULL,
                'updated_at' => '2023-08-11 21:24:04',
                'url' => 'https://sisaf.test/admin/materiales/0',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36',
                'user_id' => 2,
                'user_type' => 'App\\Models\\User',
            ),
            7 => 
            array (
                'auditable_id' => 1,
                'auditable_type' => 'App\\Models\\Materiales',
                'created_at' => '2023-08-11 21:24:04',
                'deleted_at' => NULL,
                'event' => 'deleted',
                'id' => 8,
                'ip_address' => '127.0.0.1',
                'new_values' => '[]',
                'old_values' => '{"id":1,"name":"Pinzas","descripcion":"Pinzas de disecci\\u00f3n o pinzas m\\u00e9dicas","costo":"20","cantidad":"2","costo_ultimo":"20"}',
                'tags' => NULL,
                'updated_at' => '2023-08-11 21:24:04',
                'url' => 'https://sisaf.test/admin/materiales/0',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36',
                'user_id' => 2,
                'user_type' => 'App\\Models\\User',
            ),
            8 => 
            array (
                'auditable_id' => 3,
                'auditable_type' => 'App\\Models\\Materiales',
                'created_at' => '2023-08-11 21:25:13',
                'deleted_at' => NULL,
                'event' => 'restored',
                'id' => 9,
                'ip_address' => '127.0.0.1',
                'new_values' => '{"id":3,"name":"prueba","descripcion":"Pinzas de disecci\\u00f3n o pinzas m\\u00e9dicas","costo":"20","cantidad":"123","costo_ultimo":"123"}',
                'old_values' => '[]',
                'tags' => NULL,
                'updated_at' => '2023-08-11 21:25:13',
                'url' => 'https://sisaf.test/admin/materiales/3/restore',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36',
                'user_id' => 2,
                'user_type' => 'App\\Models\\User',
            ),
            9 => 
            array (
                'auditable_id' => 7,
                'auditable_type' => 'App\\Models\\Cita',
                'created_at' => '2023-08-21 04:08:05',
                'deleted_at' => NULL,
                'event' => 'created',
                'id' => 10,
                'ip_address' => '127.0.0.1',
                'new_values' => '{"user_id":"2","date":"2023-08-21T00:00:00.000000Z","time":"15:10","id":7}',
                'old_values' => '[]',
                'tags' => NULL,
                'updated_at' => '2023-08-21 04:08:05',
                'url' => 'https://sisaf.test/admin/citas',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36',
                'user_id' => 2,
                'user_type' => 'App\\Models\\User',
            ),
            10 => 
            array (
                'auditable_id' => 2,
                'auditable_type' => 'App\\Models\\Servicios',
                'created_at' => '2023-10-02 00:46:45',
                'deleted_at' => NULL,
                'event' => 'created',
                'id' => 11,
                'ip_address' => '192.168.1.200',
                'new_values' => '{"name":"Enfermer\\u00eda","precio":"50","id":2}',
                'old_values' => '[]',
                'tags' => NULL,
                'updated_at' => '2023-10-02 00:46:45',
                'url' => 'https://sisaf.test/admin/servicios',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36',
                'user_id' => 2,
                'user_type' => 'App\\Models\\User',
            ),
            11 => 
            array (
                'auditable_id' => 3,
                'auditable_type' => 'App\\Models\\Servicios',
                'created_at' => '2023-10-02 00:47:03',
                'deleted_at' => NULL,
                'event' => 'created',
                'id' => 12,
                'ip_address' => '192.168.1.200',
                'new_values' => '{"name":"Consultorio M\\u00e9dico","precio":"75","id":3}',
                'old_values' => '[]',
                'tags' => NULL,
                'updated_at' => '2023-10-02 00:47:03',
                'url' => 'https://sisaf.test/admin/servicios',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36',
                'user_id' => 2,
                'user_type' => 'App\\Models\\User',
            ),
            12 => 
            array (
                'auditable_id' => 2,
                'auditable_type' => 'App\\Models\\User',
                'created_at' => '2023-11-15 21:08:25',
                'deleted_at' => NULL,
                'event' => 'updated',
                'id' => 13,
                'ip_address' => '127.0.0.1',
                'new_values' => '{"remember_token":"QsuBNSf6jpdghEPLvZhZJPMFM7pCe3WHmtQ5n8hZ8g2QqxvVBgEIbHpEm9CJ"}',
                'old_values' => '{"remember_token":"E2fdbGWLJQ2t39tvfizZP3XZLJNPQQUbdEej9cVLcfLumChmzQH7KNl5nelI"}',
                'tags' => NULL,
                'updated_at' => '2023-11-15 21:08:25',
                'url' => 'http://sisaf.test/admin/logout',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36',
                'user_id' => 2,
                'user_type' => 'App\\Models\\User',
            ),
            13 => 
            array (
                'auditable_id' => 4,
                'auditable_type' => 'App\\Models\\User',
                'created_at' => '2023-11-15 21:15:11',
                'deleted_at' => NULL,
                'event' => 'updated',
                'id' => 14,
                'ip_address' => '127.0.0.1',
                'new_values' => '{"password":"$2y$10$3YtP9CBw7biiTPQW7IExO.ErrYFaikGxdtnZK4ob5d.t6IsuY1uk."}',
                'old_values' => '{"password":"$2y$10$kYGoMsa.vx.MEahHz\\/yoOurrqA\\/SGIvA1Opbxjj3wlNoqrRAAbKfS"}',
                'tags' => NULL,
                'updated_at' => '2023-11-15 21:15:11',
                'url' => 'https://sisaf.test/admin/users/4',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36',
                'user_id' => 2,
                'user_type' => 'App\\Models\\User',
            ),
            14 => 
            array (
                'auditable_id' => 2,
                'auditable_type' => 'App\\Models\\User',
                'created_at' => '2023-11-15 21:17:39',
                'deleted_at' => NULL,
                'event' => 'updated',
                'id' => 15,
                'ip_address' => '127.0.0.1',
                'new_values' => '{"remember_token":"j6XBSlRS8WaqLWl5DAT3q8hKs9WSTrIvusUe9uVTHZ9QaXpSRGpAimoiq39H"}',
                'old_values' => '{"remember_token":"QsuBNSf6jpdghEPLvZhZJPMFM7pCe3WHmtQ5n8hZ8g2QqxvVBgEIbHpEm9CJ"}',
                'tags' => NULL,
                'updated_at' => '2023-11-15 21:17:39',
                'url' => 'https://sisaf.test/admin/logout',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36',
                'user_id' => 2,
                'user_type' => 'App\\Models\\User',
            ),
            15 => 
            array (
                'auditable_id' => 1,
                'auditable_type' => 'App\\Models\\User',
                'created_at' => '2023-11-15 21:22:58',
                'deleted_at' => NULL,
                'event' => 'updated',
                'id' => 16,
                'ip_address' => '127.0.0.1',
                'new_values' => '{"remember_token":"6pE1YvHj3wNhGYGjnn7ZdLKQeUxWVux0OLQjVQjblDluE4VZEvMsjXjqBYtl"}',
                'old_values' => '{"remember_token":"zUQTWKZzBAqMeNj7vjZRavgzpT3IQsaKAFFzFl7zQMEgkkogxGbpuXDsel2s"}',
                'tags' => NULL,
                'updated_at' => '2023-11-15 21:22:58',
                'url' => 'https://sisaf.test/admin/logout',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36',
                'user_id' => 1,
                'user_type' => 'App\\Models\\User',
            ),
            16 => 
            array (
                'auditable_id' => 2,
                'auditable_type' => 'App\\Models\\User',
                'created_at' => '2023-11-19 21:34:12',
                'deleted_at' => NULL,
                'event' => 'updated',
                'id' => 17,
                'ip_address' => '127.0.0.1',
                'new_values' => '{"remember_token":"OrskPaESAGn94Yg7ZEUPc7Ezqxjg7B5gmqJgPseCYzKKpqw3tUKPQjcRhxXi"}',
                'old_values' => '{"remember_token":"j6XBSlRS8WaqLWl5DAT3q8hKs9WSTrIvusUe9uVTHZ9QaXpSRGpAimoiq39H"}',
                'tags' => NULL,
                'updated_at' => '2023-11-19 21:34:12',
                'url' => 'https://sisaf.test/admin/logout',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36',
                'user_id' => 2,
                'user_type' => 'App\\Models\\User',
            ),
            17 => 
            array (
                'auditable_id' => 5,
                'auditable_type' => 'App\\Models\\User',
                'created_at' => '2023-11-24 19:00:12',
                'deleted_at' => NULL,
                'event' => 'created',
                'id' => 18,
                'ip_address' => '127.0.0.1',
                'new_values' => '{"name":"Dr Osorio","email":"osorio123@gmail.com","password":"$2y$10$BFEyvg8H3s0MbuVWbs2unu.oSz\\/B6nFT.T5UfOrCBrtm0ByYnYeuW","avatar":"users\\/default.png","role_id":"8","settings":"{\\"locale\\":\\"es\\"}","id":5}',
                'old_values' => '[]',
                'tags' => NULL,
                'updated_at' => '2023-11-24 19:00:12',
                'url' => 'https://sisaf.test/admin/users',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36',
                'user_id' => 2,
                'user_type' => 'App\\Models\\User',
            ),
            18 => 
            array (
                'auditable_id' => 5,
                'auditable_type' => 'App\\Models\\User',
                'created_at' => '2023-11-24 19:02:33',
                'deleted_at' => NULL,
                'event' => 'updated',
                'id' => 19,
                'ip_address' => '127.0.0.1',
                'new_values' => '{"role_id":"6"}',
                'old_values' => '{"role_id":8}',
                'tags' => NULL,
                'updated_at' => '2023-11-24 19:02:33',
                'url' => 'https://sisaf.test/admin/users/5',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36',
                'user_id' => 2,
                'user_type' => 'App\\Models\\User',
            ),
            19 => 
            array (
                'auditable_id' => 6,
                'auditable_type' => 'App\\Models\\User',
                'created_at' => '2023-11-24 19:03:28',
                'deleted_at' => NULL,
                'event' => 'created',
                'id' => 20,
                'ip_address' => '127.0.0.1',
                'new_values' => '{"name":"Enfermera Guadalupe","email":"guadalupe33@gmail.com","password":"$2y$10$8ZpSWlurgR1XDb7T3ZSOn.CPsw6wvwyqpr92H8M9SxPEz2w\\/wpCye","avatar":"users\\/default.png","role_id":"3","id":6}',
                'old_values' => '[]',
                'tags' => NULL,
                'updated_at' => '2023-11-24 19:03:28',
                'url' => 'https://sisaf.test/admin/users',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36',
                'user_id' => 2,
                'user_type' => 'App\\Models\\User',
            ),
            20 => 
            array (
                'auditable_id' => 6,
                'auditable_type' => 'App\\Models\\User',
                'created_at' => '2023-11-26 09:14:31',
                'deleted_at' => NULL,
                'event' => 'deleted',
                'id' => 21,
                'ip_address' => '127.0.0.1',
                'new_values' => '[]',
                'old_values' => '{"id":6,"role_id":3,"name":"Enfermera Guadalupe","email":"guadalupe33@gmail.com","avatar":"users\\/default.png","email_verified_at":null,"password":"$2y$10$8ZpSWlurgR1XDb7T3ZSOn.CPsw6wvwyqpr92H8M9SxPEz2w\\/wpCye","remember_token":null,"settings":null}',
                'tags' => NULL,
                'updated_at' => '2023-11-26 09:14:31',
                'url' => 'https://sisaf.test/admin/users/6',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36',
                'user_id' => 2,
                'user_type' => 'App\\Models\\User',
            ),
            21 => 
            array (
                'auditable_id' => 969,
                'auditable_type' => 'App\\Models\\Pacientes',
                'created_at' => '2023-11-27 20:43:06',
                'deleted_at' => NULL,
                'event' => 'created',
                'id' => 22,
                'ip_address' => '127.0.0.1',
                'new_values' => '{"name":"aw","last_name":"wa","email":"wa","direccion":"wa","sexo":"radio1","fecha_de_nacimiento":"wa","ciudad":"wa","id":969}',
                'old_values' => '[]',
                'tags' => NULL,
                'updated_at' => '2023-11-27 20:43:06',
                'url' => 'https://sisaf.test/admin/pacientes',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36',
                'user_id' => 2,
                'user_type' => 'App\\Models\\User',
            ),
            22 => 
            array (
                'auditable_id' => 969,
                'auditable_type' => 'App\\Models\\Pacientes',
                'created_at' => '2023-11-27 20:43:39',
                'deleted_at' => NULL,
                'event' => 'deleted',
                'id' => 23,
                'ip_address' => '127.0.0.1',
                'new_values' => '[]',
                'old_values' => '{"id":969,"name":"aw","last_name":"wa","email":"wa","direccion":"wa","sexo":"radio1","fecha_de_nacimiento":"wa","ciudad":"wa"}',
                'tags' => NULL,
                'updated_at' => '2023-11-27 20:43:39',
                'url' => 'https://sisaf.test/admin/pacientes/969',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36',
                'user_id' => 2,
                'user_type' => 'App\\Models\\User',
            ),
            23 => 
            array (
                'auditable_id' => 12,
                'auditable_type' => 'App\\Models\\User',
                'created_at' => '2023-11-27 22:50:16',
                'deleted_at' => NULL,
                'event' => 'created',
                'id' => 24,
                'ip_address' => '127.0.0.1',
                'new_values' => '{"name":"qwewqeqweqwe","email":"wfernando.aguilarm@gmail","password":"$2y$10$sBVL1cFGJt8lvJdKiADN1eR\\/WEHKqiFurK9o6ABnsHETV9.y1h9Sa","avatar":"users\\/default.png","role_id":"1","id":12}',
                'old_values' => '[]',
                'tags' => NULL,
                'updated_at' => '2023-11-27 22:50:16',
                'url' => 'https://sisaf.test/admin/users',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36',
                'user_id' => 2,
                'user_type' => 'App\\Models\\User',
            ),
            24 => 
            array (
                'auditable_id' => 12,
                'auditable_type' => 'App\\Models\\User',
                'created_at' => '2023-11-27 22:50:24',
                'deleted_at' => NULL,
                'event' => 'deleted',
                'id' => 25,
                'ip_address' => '127.0.0.1',
                'new_values' => '[]',
                'old_values' => '{"id":12,"role_id":1,"name":"qwewqeqweqwe","email":"wfernando.aguilarm@gmail","avatar":"users\\/default.png","email_verified_at":null,"password":"$2y$10$sBVL1cFGJt8lvJdKiADN1eR\\/WEHKqiFurK9o6ABnsHETV9.y1h9Sa","remember_token":null,"settings":null}',
                'tags' => NULL,
                'updated_at' => '2023-11-27 22:50:24',
                'url' => 'https://sisaf.test/admin/users/12',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36',
                'user_id' => 2,
                'user_type' => 'App\\Models\\User',
            ),
            25 => 
            array (
                'auditable_id' => 13,
                'auditable_type' => 'App\\Models\\User',
                'created_at' => '2023-11-27 22:53:15',
                'deleted_at' => NULL,
                'event' => 'created',
                'id' => 26,
                'ip_address' => '127.0.0.1',
                'new_values' => '{"name":"Walter Aguilar","email":"wfernando.aguilar@gmail.com","password":"$2y$10$spAYhDQ9Di\\/e6qe\\/BMj0F.2SfVsmTwhvLIyIRi49tBUATq8cxZygm","avatar":"users\\/default.png","role_id":"1","id":13}',
                'old_values' => '[]',
                'tags' => NULL,
                'updated_at' => '2023-11-27 22:53:15',
                'url' => 'https://sisaf.test/admin/users',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36',
                'user_id' => 2,
                'user_type' => 'App\\Models\\User',
            ),
            26 => 
            array (
                'auditable_id' => 14,
                'auditable_type' => 'App\\Models\\User',
                'created_at' => '2023-11-28 00:26:18',
                'deleted_at' => NULL,
                'event' => 'created',
                'id' => 27,
                'ip_address' => '127.0.0.1',
                'new_values' => '{"name":"Walter Aguilar","email":"wfernando.aguilar@d","password":"$2y$10$Xw\\/d0A9rYo7JegMvc0LQi.y4tGIncVGqoSNTqRBV0SbaWLvonSKO6","avatar":"users\\/default.png","role_id":"1","id":14}',
                'old_values' => '[]',
                'tags' => NULL,
                'updated_at' => '2023-11-28 00:26:18',
                'url' => 'https://sisaf.test/admin/users',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36',
                'user_id' => 2,
                'user_type' => 'App\\Models\\User',
            ),
            27 => 
            array (
                'auditable_id' => 14,
                'auditable_type' => 'App\\Models\\User',
                'created_at' => '2023-11-28 00:26:28',
                'deleted_at' => NULL,
                'event' => 'deleted',
                'id' => 28,
                'ip_address' => '127.0.0.1',
                'new_values' => '[]',
                'old_values' => '{"id":14,"role_id":1,"name":"Walter Aguilar","email":"wfernando.aguilar@d","avatar":"users\\/default.png","email_verified_at":null,"password":"$2y$10$Xw\\/d0A9rYo7JegMvc0LQi.y4tGIncVGqoSNTqRBV0SbaWLvonSKO6","remember_token":null,"settings":null}',
                'tags' => NULL,
                'updated_at' => '2023-11-28 00:26:28',
                'url' => 'https://sisaf.test/admin/users/14',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36',
                'user_id' => 2,
                'user_type' => 'App\\Models\\User',
            ),
        ));
        
        
    }
}