<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class AuditsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('audits')->delete();
        
        \DB::table('audits')->insert(array (
            0 => 
            array (
                'auditable_id' => 2,
                'auditable_type' => 'App\\Models\\Servicios',
                'created_at' => '2023-07-25 01:03:53',
                'deleted_at' => NULL,
                'event' => 'created',
                'id' => 1,
                'ip_address' => '127.0.0.1',
                'new_values' => '{"name":"Traumatolog\\u00eda","precio":"250","id":2}',
                'old_values' => '[]',
                'tags' => NULL,
                'updated_at' => '2023-07-31 21:59:35',
                'url' => 'https://sisaf.test/admin/servicios',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36',
                'user_id' => 2,
                'user_type' => 'App\\Models\\User',
            ),
            1 => 
            array (
                'auditable_id' => 2,
                'auditable_type' => 'App\\Models\\Materiales',
                'created_at' => '2023-08-03 00:40:16',
                'deleted_at' => NULL,
                'event' => 'updated',
                'id' => 2,
                'ip_address' => '127.0.0.1',
                'new_values' => '{"name":"Jeringas 1cc"}',
                'old_values' => '{"name":"Jeringas"}',
                'tags' => NULL,
                'updated_at' => '2023-08-03 00:40:16',
                'url' => 'https://sisaf.test/admin/materiales/2',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36',
                'user_id' => 2,
                'user_type' => 'App\\Models\\User',
            ),
            2 => 
            array (
                'auditable_id' => 1,
                'auditable_type' => 'App\\Models\\Materiales',
                'created_at' => '2023-08-11 21:18:22',
                'deleted_at' => NULL,
                'event' => 'deleted',
                'id' => 3,
                'ip_address' => '127.0.0.1',
                'new_values' => '[]',
                'old_values' => '{"id":1,"name":"Pinzas","descripcion":"Pinzas de disecci\\u00f3n o pinzas m\\u00e9dicas","costo":"20","cantidad":"2","costo_ultimo":"20"}',
                'tags' => NULL,
                'updated_at' => '2023-08-11 21:18:22',
                'url' => 'https://sisaf.test/admin/materiales/1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36',
                'user_id' => 2,
                'user_type' => 'App\\Models\\User',
            ),
            3 => 
            array (
                'auditable_id' => 1,
                'auditable_type' => 'App\\Models\\Materiales',
                'created_at' => '2023-08-11 21:23:24',
                'deleted_at' => NULL,
                'event' => 'restored',
                'id' => 4,
                'ip_address' => '127.0.0.1',
                'new_values' => '{"id":1,"name":"Pinzas","descripcion":"Pinzas de disecci\\u00f3n o pinzas m\\u00e9dicas","costo":"20","cantidad":"2","costo_ultimo":"20"}',
                'old_values' => '[]',
                'tags' => NULL,
                'updated_at' => '2023-08-11 21:23:24',
                'url' => 'https://sisaf.test/admin/materiales/1/restore',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36',
                'user_id' => 2,
                'user_type' => 'App\\Models\\User',
            ),
            4 => 
            array (
                'auditable_id' => 3,
                'auditable_type' => 'App\\Models\\Materiales',
                'created_at' => '2023-08-11 21:23:43',
                'deleted_at' => NULL,
                'event' => 'created',
                'id' => 5,
                'ip_address' => '127.0.0.1',
                'new_values' => '{"name":"prueba","descripcion":"Pinzas de disecci\\u00f3n o pinzas m\\u00e9dicas","costo":"20","cantidad":"123","costo_ultimo":"123","id":3}',
                'old_values' => '[]',
                'tags' => NULL,
                'updated_at' => '2023-08-11 21:23:43',
                'url' => 'https://sisaf.test/admin/materiales',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36',
                'user_id' => 2,
                'user_type' => 'App\\Models\\User',
            ),
            5 => 
            array (
                'auditable_id' => 3,
                'auditable_type' => 'App\\Models\\Materiales',
                'created_at' => '2023-08-11 21:23:51',
                'deleted_at' => NULL,
                'event' => 'deleted',
                'id' => 6,
                'ip_address' => '127.0.0.1',
                'new_values' => '[]',
                'old_values' => '{"id":3,"name":"prueba","descripcion":"Pinzas de disecci\\u00f3n o pinzas m\\u00e9dicas","costo":"20","cantidad":"123","costo_ultimo":"123"}',
                'tags' => NULL,
                'updated_at' => '2023-08-11 21:23:51',
                'url' => 'https://sisaf.test/admin/materiales/0',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36',
                'user_id' => 2,
                'user_type' => 'App\\Models\\User',
            ),
            6 => 
            array (
                'auditable_id' => 2,
                'auditable_type' => 'App\\Models\\Materiales',
                'created_at' => '2023-08-11 21:24:04',
                'deleted_at' => NULL,
                'event' => 'deleted',
                'id' => 7,
                'ip_address' => '127.0.0.1',
                'new_values' => '[]',
                'old_values' => '{"id":2,"name":"Jeringas 1cc","descripcion":"1 cc. o ml. Aguja de calibre de 27x5\\/8\\", Se coloca en 0\\u00ba - Para intrad\\u00e9rmicas","costo":"20","cantidad":"10","costo_ultimo":"20"}',
                'tags' => NULL,
                'updated_at' => '2023-08-11 21:24:04',
                'url' => 'https://sisaf.test/admin/materiales/0',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36',
                'user_id' => 2,
                'user_type' => 'App\\Models\\User',
            ),
            7 => 
            array (
                'auditable_id' => 1,
                'auditable_type' => 'App\\Models\\Materiales',
                'created_at' => '2023-08-11 21:24:04',
                'deleted_at' => NULL,
                'event' => 'deleted',
                'id' => 8,
                'ip_address' => '127.0.0.1',
                'new_values' => '[]',
                'old_values' => '{"id":1,"name":"Pinzas","descripcion":"Pinzas de disecci\\u00f3n o pinzas m\\u00e9dicas","costo":"20","cantidad":"2","costo_ultimo":"20"}',
                'tags' => NULL,
                'updated_at' => '2023-08-11 21:24:04',
                'url' => 'https://sisaf.test/admin/materiales/0',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36',
                'user_id' => 2,
                'user_type' => 'App\\Models\\User',
            ),
            8 => 
            array (
                'auditable_id' => 3,
                'auditable_type' => 'App\\Models\\Materiales',
                'created_at' => '2023-08-11 21:25:13',
                'deleted_at' => NULL,
                'event' => 'restored',
                'id' => 9,
                'ip_address' => '127.0.0.1',
                'new_values' => '{"id":3,"name":"prueba","descripcion":"Pinzas de disecci\\u00f3n o pinzas m\\u00e9dicas","costo":"20","cantidad":"123","costo_ultimo":"123"}',
                'old_values' => '[]',
                'tags' => NULL,
                'updated_at' => '2023-08-11 21:25:13',
                'url' => 'https://sisaf.test/admin/materiales/3/restore',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36',
                'user_id' => 2,
                'user_type' => 'App\\Models\\User',
            ),
            9 => 
            array (
                'auditable_id' => 2,
                'auditable_type' => 'App\\Models\\Materiales',
                'created_at' => '2023-08-11 21:25:16',
                'deleted_at' => NULL,
                'event' => 'restored',
                'id' => 10,
                'ip_address' => '127.0.0.1',
                'new_values' => '{"id":2,"name":"Jeringas 1cc","descripcion":"1 cc. o ml. Aguja de calibre de 27x5\\/8\\", Se coloca en 0\\u00ba - Para intrad\\u00e9rmicas","costo":"20","cantidad":"10","costo_ultimo":"20"}',
                'old_values' => '[]',
                'tags' => NULL,
                'updated_at' => '2023-08-11 21:25:16',
                'url' => 'https://sisaf.test/admin/materiales/2/restore',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36',
                'user_id' => 2,
                'user_type' => 'App\\Models\\User',
            ),
            10 => 
            array (
                'auditable_id' => 1,
                'auditable_type' => 'App\\Models\\Materiales',
                'created_at' => '2023-08-11 21:25:19',
                'deleted_at' => NULL,
                'event' => 'restored',
                'id' => 11,
                'ip_address' => '127.0.0.1',
                'new_values' => '{"id":1,"name":"Pinzas","descripcion":"Pinzas de disecci\\u00f3n o pinzas m\\u00e9dicas","costo":"20","cantidad":"2","costo_ultimo":"20"}',
                'old_values' => '[]',
                'tags' => NULL,
                'updated_at' => '2023-08-11 21:25:19',
                'url' => 'https://sisaf.test/admin/materiales/1/restore',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36',
                'user_id' => 2,
                'user_type' => 'App\\Models\\User',
            ),
            11 => 
            array (
                'auditable_id' => 2,
                'auditable_type' => 'App\\Models\\User',
                'created_at' => '2023-08-15 02:45:46',
                'deleted_at' => NULL,
                'event' => 'updated',
                'id' => 14,
                'ip_address' => '127.0.0.1',
                'new_values' => '{"remember_token":"rDHnXPoSXiz7ZWxfieyNOIybiGphTDh85AUAAMRycRuqpOP2cvOqR4VrZm02"}',
                'old_values' => '{"remember_token":"aYrVpeOEGwSterJODTgHzV0gulgBWdJSy6H398DPhRImps2VW7trTQUL6hI1"}',
                'tags' => NULL,
                'updated_at' => '2023-08-15 02:45:46',
                'url' => 'https://sisaf.test/admin/logout',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36',
                'user_id' => 2,
                'user_type' => 'App\\Models\\User',
            ),
            12 => 
            array (
                'auditable_id' => 4,
                'auditable_type' => 'App\\Models\\Cita',
                'created_at' => '2023-08-21 02:46:48',
                'deleted_at' => NULL,
                'event' => 'created',
                'id' => 15,
                'ip_address' => '127.0.0.1',
                'new_values' => '{"user_id":"1","date":"2023-08-21T00:00:00.000000Z","time":"17:31","id":4}',
                'old_values' => '[]',
                'tags' => NULL,
                'updated_at' => '2023-08-21 02:46:48',
                'url' => 'https://sisaf.test/admin/citas',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36',
                'user_id' => 2,
                'user_type' => 'App\\Models\\User',
            ),
            13 => 
            array (
                'auditable_id' => 4,
                'auditable_type' => 'App\\Models\\Cita',
                'created_at' => '2023-08-21 03:19:21',
                'deleted_at' => NULL,
                'event' => 'updated',
                'id' => 16,
                'ip_address' => '127.0.0.1',
                'new_values' => '{"date":"2023-08-21T00:00:00.000000Z","time":"04:25"}',
                'old_values' => '{"date":"2023-08-21","time":"17:31:00"}',
                'tags' => NULL,
                'updated_at' => '2023-08-21 03:19:21',
                'url' => 'https://sisaf.test/admin/citas/4',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36',
                'user_id' => 2,
                'user_type' => 'App\\Models\\User',
            ),
            14 => 
            array (
                'auditable_id' => 5,
                'auditable_type' => 'App\\Models\\Cita',
                'created_at' => '2023-08-21 03:26:58',
                'deleted_at' => NULL,
                'event' => 'created',
                'id' => 17,
                'ip_address' => '127.0.0.1',
                'new_values' => '{"user_id":"2","date":"2023-08-21T00:00:00.000000Z","time":"16:28","id":5}',
                'old_values' => '[]',
                'tags' => NULL,
                'updated_at' => '2023-08-21 03:26:58',
                'url' => 'https://sisaf.test/admin/citas',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36',
                'user_id' => 2,
                'user_type' => 'App\\Models\\User',
            ),
            15 => 
            array (
                'auditable_id' => 6,
                'auditable_type' => 'App\\Models\\Cita',
                'created_at' => '2023-08-21 03:44:41',
                'deleted_at' => NULL,
                'event' => 'created',
                'id' => 18,
                'ip_address' => '127.0.0.1',
                'new_values' => '{"user_id":"1","date":"2023-08-21T00:00:00.000000Z","time":"10:37","id":6}',
                'old_values' => '[]',
                'tags' => NULL,
                'updated_at' => '2023-08-21 03:44:41',
                'url' => 'https://sisaf.test/admin/citas',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36',
                'user_id' => 2,
                'user_type' => 'App\\Models\\User',
            ),
            16 => 
            array (
                'auditable_id' => 7,
                'auditable_type' => 'App\\Models\\Cita',
                'created_at' => '2023-08-21 04:08:05',
                'deleted_at' => NULL,
                'event' => 'created',
                'id' => 19,
                'ip_address' => '127.0.0.1',
                'new_values' => '{"user_id":"2","date":"2023-08-21T00:00:00.000000Z","time":"15:10","id":7}',
                'old_values' => '[]',
                'tags' => NULL,
                'updated_at' => '2023-08-21 04:08:05',
                'url' => 'https://sisaf.test/admin/citas',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36',
                'user_id' => 2,
                'user_type' => 'App\\Models\\User',
            ),
            17 => 
            array (
                'auditable_id' => 1,
                'auditable_type' => 'App\\Models\\Cita',
                'created_at' => '2023-08-21 20:49:48',
                'deleted_at' => NULL,
                'event' => 'created',
                'id' => 20,
                'ip_address' => '127.0.0.1',
                'new_values' => '{"motivo":"Ecografia","user_id":"2","servicio_id":"1","date":"2023-08-22T04:00:00.000000Z","time":"06:50","paciente_id":"105","id":1}',
                'old_values' => '[]',
                'tags' => NULL,
                'updated_at' => '2023-08-21 20:49:48',
                'url' => 'https://sisaf.test/admin/citas',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36',
                'user_id' => 2,
                'user_type' => 'App\\Models\\User',
            ),
            18 => 
            array (
                'auditable_id' => 2,
                'auditable_type' => 'App\\Models\\Cita',
                'created_at' => '2023-08-21 20:50:17',
                'deleted_at' => NULL,
                'event' => 'created',
                'id' => 21,
                'ip_address' => '127.0.0.1',
                'new_values' => '{"motivo":"Ecografia","user_id":"2","servicio_id":"1","date":"2023-08-22T04:00:00.000000Z","time":"06:50","paciente_id":"105","id":2}',
                'old_values' => '[]',
                'tags' => NULL,
                'updated_at' => '2023-08-21 20:50:17',
                'url' => 'https://sisaf.test/admin/citas',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36',
                'user_id' => 2,
                'user_type' => 'App\\Models\\User',
            ),
            19 => 
            array (
                'auditable_id' => 3,
                'auditable_type' => 'App\\Models\\Cita',
                'created_at' => '2023-08-21 20:55:44',
                'deleted_at' => NULL,
                'event' => 'created',
                'id' => 22,
                'ip_address' => '127.0.0.1',
                'new_values' => '{"motivo":"Ecografia","user_id":"2","servicio_id":"1","date":"2023-08-23T04:00:00.000000Z","time":"22:00","paciente_id":"105","id":3}',
                'old_values' => '[]',
                'tags' => NULL,
                'updated_at' => '2023-08-21 20:55:44',
                'url' => 'https://sisaf.test/admin/citas',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36',
                'user_id' => 2,
                'user_type' => 'App\\Models\\User',
            ),
            20 => 
            array (
                'auditable_id' => 4,
                'auditable_type' => 'App\\Models\\Cita',
                'created_at' => '2023-08-21 21:02:04',
                'deleted_at' => NULL,
                'event' => 'created',
                'id' => 23,
                'ip_address' => '127.0.0.1',
                'new_values' => '{"motivo":"Revision","user_id":"2","servicio_id":"1","date":"2023-08-22T04:00:00.000000Z","time":"06:00","paciente_id":"105","id":4}',
                'old_values' => '[]',
                'tags' => NULL,
                'updated_at' => '2023-08-21 21:02:04',
                'url' => 'https://sisaf.test/admin/citas',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36',
                'user_id' => 2,
                'user_type' => 'App\\Models\\User',
            ),
        ));
        
        
    }
}