<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class DataRowsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('data_rows')->delete();

        \DB::table('data_rows')->insert(array (
            0 =>
            array (
                'id' => 1,
                'data_type_id' => 1,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'ID',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            1 =>
            array (
                'id' => 2,
                'data_type_id' => 1,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Nombre',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":["required","min:2","max:40"],"messages":{"required":"El :attribute es obligatorio.","min":"El :attribute debe tener :min caracteres como m\\u00ednimo.","max":"El :attribute debe tener :max caracteres como m\\u00e1ximo."}}}',
                'order' => 2,
            ),
            2 =>
            array (
                'id' => 3,
                'data_type_id' => 1,
                'field' => 'email',
                'type' => 'text',
                'display_name' => 'Correo Electrónico',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
            'details' => '{"validation":{"rule":["required","min:8","unique:users","regex:\\/^[a-z0-9!#$%&\'*+\\\\\\/=?^_`{|}~-]+(?:\\\\.[a-z0-9!#$%&\'*+\\\\\\/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\\\\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$\\/","max:40"],"messages":{"required":"El :attribute es obligatorio.","min":"El :attribute debe tener :min caracteres como m\\u00ednimo.","unique":"El :attribute debe ser \\u00fanico. Este :attribute ya existe en la base de datos.","regex":"El :attribute debe ser v\\u00e1lido.","max":"El :attribute debe tener :max caracteres como m\\u00e1ximo."}}}',
                'order' => 3,
            ),
            3 =>
            array (
                'id' => 4,
                'data_type_id' => 1,
                'field' => 'password',
                'type' => 'password',
                'display_name' => 'Constraseña',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"validation":{"rule":["min:6","max:40"],"add":{"rule":"required"},"edit":{"rule":"nullable"},"messages":{"required":"EL :attribute es obligatorio.","min":"La :attribute debe tener :min caracteres como m\\u00ednimo.","max":"El :attribute debe tener :max caracteres como m\\u00e1ximo."}}}',
                'order' => 4,
            ),
            4 =>
            array (
                'id' => 5,
                'data_type_id' => 1,
                'field' => 'remember_token',
                'type' => 'text',
                'display_name' => 'Token de Recuerdo',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 5,
            ),
            5 =>
            array (
                'id' => 6,
                'data_type_id' => 1,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Creado el',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 11,
            ),
            6 =>
            array (
                'id' => 7,
                'data_type_id' => 1,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Actualizado el',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 12,
            ),
            7 =>
            array (
                'id' => 8,
                'data_type_id' => 1,
                'field' => 'avatar',
                'type' => 'image',
                'display_name' => 'Avatar',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 7,
            ),
            8 =>
            array (
                'id' => 9,
                'data_type_id' => 1,
                'field' => 'user_belongsto_role_relationship',
                'type' => 'relationship',
                'display_name' => 'Rol',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"model":"TCG\\\\Voyager\\\\Models\\\\Role","table":"roles","type":"belongsTo","column":"role_id","key":"id","label":"display_name","pivot_table":"roles","pivot":"0","taggable":"0"}',
                'order' => 9,
            ),
            9 =>
            array (
                'id' => 10,
                'data_type_id' => 1,
                'field' => 'settings',
                'type' => 'hidden',
                'display_name' => 'Ajustes',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 10,
            ),
            10 =>
            array (
                'id' => 11,
                'data_type_id' => 2,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'ID',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 1,
            ),
            11 =>
            array (
                'id' => 12,
                'data_type_id' => 2,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Nombre',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 2,
            ),
            12 =>
            array (
                'id' => 13,
                'data_type_id' => 2,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Creado',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 3,
            ),
            13 =>
            array (
                'id' => 14,
                'data_type_id' => 2,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Actualizado',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 4,
            ),
            14 =>
            array (
                'id' => 15,
                'data_type_id' => 3,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'ID',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            15 =>
            array (
                'id' => 16,
                'data_type_id' => 3,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Nombre',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 2,
            ),
            16 =>
            array (
                'id' => 17,
                'data_type_id' => 3,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Creado',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 3,
            ),
            17 =>
            array (
                'id' => 18,
                'data_type_id' => 3,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Actualizado',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 4,
            ),
            18 =>
            array (
                'id' => 19,
                'data_type_id' => 3,
                'field' => 'display_name',
                'type' => 'text',
                'display_name' => 'Nombre a Mostrar',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 5,
            ),
            19 =>
            array (
                'id' => 20,
                'data_type_id' => 1,
                'field' => 'role_id',
                'type' => 'text',
                'display_name' => 'Rol',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":["required"],"messages":{"required":"El :attribute es obligatorio."}}}',
                'order' => 8,
            ),
            20 =>
            array (
                'id' => 21,
                'data_type_id' => 6,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            21 =>
            array (
                'id' => 22,
                'data_type_id' => 6,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 1,
                'details' => '{}',
                'order' => 2,
            ),
            22 =>
            array (
                'id' => 23,
                'data_type_id' => 6,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 3,
            ),
            23 =>
            array (
                'id' => 24,
                'data_type_id' => 7,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            24 =>
            array (
                'id' => 25,
                'data_type_id' => 7,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Nombre',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":["required","min:3"],"messages":{"required":"El :attribute es obligatorio.","min":"El :attribute debe tener :min caracteres como m\\u00ednimo."}}}',
                'order' => 2,
            ),
            25 =>
            array (
                'id' => 26,
                'data_type_id' => 7,
                'field' => 'descripcion',
                'type' => 'text',
                'display_name' => 'Descripcion',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":["required","min:3"],"messages":{"required":"El :attribute es obligatorio.","min":"El :attribute debe tener :min caracteres como m\\u00ednimo."}}}',
                'order' => 3,
            ),
            26 =>
            array (
                'id' => 27,
                'data_type_id' => 7,
                'field' => 'costo',
                'type' => 'number',
                'display_name' => 'Costo',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":["required","min:1"],"messages":{"required":"El :attribute es obligatorio.","min":"El :attribute debe tener :min caracteres como m\\u00ednimo."}}}',
                'order' => 4,
            ),
            27 =>
            array (
                'id' => 28,
                'data_type_id' => 7,
                'field' => 'cantidad',
                'type' => 'number',
                'display_name' => 'Cantidad',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":["required","min:1"],"messages":{"required":"El :attribute es obligatorio.","min":"El :attribute debe tener :min caracteres como m\\u00ednimo."}}}',
                'order' => 5,
            ),
            28 =>
            array (
                'id' => 29,
                'data_type_id' => 7,
                'field' => 'costo_ultimo',
                'type' => 'number',
                'display_name' => 'Costo Ultimo',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":["required","min:1"],"messages":{"required":"El :attribute es obligatorio.","min":"El :attribute debe tener :min caracteres como m\\u00ednimo."}}}',
                'order' => 6,
            ),
            29 =>
            array (
                'id' => 30,
                'data_type_id' => 7,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Creado el',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 7,
            ),
            30 =>
            array (
                'id' => 31,
                'data_type_id' => 7,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Actualizado el',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 8,
            ),
            31 =>
            array (
                'id' => 32,
                'data_type_id' => 8,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            32 =>
            array (
                'id' => 33,
                'data_type_id' => 8,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Nombre',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":["required","min:3"],"messages":{"required":"El :attribute es obligatorio.","min":"El :attribute debe tener :min caracteres como m\\u00ednimo."}}}',
                'order' => 2,
            ),
            33 =>
            array (
                'id' => 34,
                'data_type_id' => 8,
                'field' => 'descripcion',
                'type' => 'text',
                'display_name' => 'Descripción',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":["required","min:3"],"messages":{"required":"El :attribute es obligatorio.","min":"El :attribute debe tener :min caracteres como m\\u00ednimo."}}}',
                'order' => 3,
            ),
            34 =>
            array (
                'id' => 35,
                'data_type_id' => 8,
                'field' => 'costo',
                'type' => 'number',
                'display_name' => 'Costo',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":["required","min:1"],"messages":{"required":"El :attribute es obligatorio.","min":"El :attribute debe tener :min caracteres como m\\u00ednimo."}}}',
                'order' => 4,
            ),
            35 =>
            array (
                'id' => 36,
                'data_type_id' => 8,
                'field' => 'cantidad',
                'type' => 'number',
                'display_name' => 'Cantidad',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":["required","min:1"],"messages":{"required":"El :attribute es obligatorio.","min":"El :attribute debe tener :min caracteres como m\\u00ednimo."}}}',
                'order' => 5,
            ),
            36 =>
            array (
                'id' => 37,
                'data_type_id' => 8,
                'field' => 'costo_ultimo',
                'type' => 'number',
                'display_name' => 'Costo Ultimo',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":["required","min:1"],"messages":{"required":"El :attribute es obligatorio.","min":"El :attribute debe tener :min caracteres como m\\u00ednimo."}}}',
                'order' => 6,
            ),
            37 =>
            array (
                'id' => 38,
                'data_type_id' => 8,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Creado el',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 7,
            ),
            38 =>
            array (
                'id' => 39,
                'data_type_id' => 8,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Actualizado el',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 8,
            ),
            39 =>
            array (
                'id' => 40,
                'data_type_id' => 9,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            40 =>
            array (
                'id' => 41,
                'data_type_id' => 9,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Nombre',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":["required","min:1","max:40"],"messages":{"required":"El :attribute es obligatorio.","min":"El :attribute debe tener :min caracteres como m\\u00ednimo.","max":"El :attribute debe tener :max caracteres como m\\u00e1ximo."}}}',
                'order' => 2,
            ),
            41 =>
            array (
                'id' => 42,
                'data_type_id' => 9,
                'field' => 'precio',
                'type' => 'number',
                'display_name' => 'Precio',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":["required","min:1"],"messages":{"required":"El :attribute es obligatorio.","min":"El :attribute debe tener :min caracteres como m\\u00ednimo."}}}',
                'order' => 3,
            ),
            42 =>
            array (
                'id' => 43,
                'data_type_id' => 9,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Creado el',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 4,
            ),
            43 =>
            array (
                'id' => 44,
                'data_type_id' => 9,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Actualizado el',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 5,
            ),
            44 =>
            array (
                'id' => 45,
                'data_type_id' => 10,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 1,
                'details' => '{}',
                'order' => 1,
            ),
            45 =>
            array (
                'id' => 46,
                'data_type_id' => 10,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Nombres',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":["required","min:3","max:30"],"messages":{"required":"El :attribute es obligatorio.","min":"El :attribute debe tener :min caracteres como m\\u00ednimo.","max":"El :attribute debe tener :max caracteres como m\\u00e1ximo."}}}',
                'order' => 4,
            ),
            46 =>
            array (
                'id' => 47,
                'data_type_id' => 10,
                'field' => 'last_name',
                'type' => 'text',
                'display_name' => 'Apellido Paterno',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":["required","min:3","max:20"],"messages":{"required":"El :attribute es obligatorio.","min":"El :attribute debe tener :min caracteres como m\\u00ednimo.","max":"El :attribute debe tener :max caracteres como m\\u00e1ximo."}}}',
                'order' => 5,
            ),
            47 =>
            array (
                'id' => 48,
                'data_type_id' => 10,
                'field' => 'email',
                'type' => 'text',
                'display_name' => 'Email',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
            'details' => '{"validation":{"rule":["required","min:5","unique:pacientes,email","regex:\\/^[a-z0-9!#$%&\'*+\\\\\\/=?^_`{|}~-]+(?:\\\\.[a-z0-9!#$%&\'*+\\\\\\/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\\\\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$\\/","max:60"],"messages":{"required":"El :attribute es obligatorio.","min":"El :attribute debe tener :min caracteres como m\\u00ednimo.","unique":"El :attribute debe ser \\u00fanico. Este :attribute ya existe en la base de datos.","regex":"El :attribute ser v\\u00e1lido.","max":"El :attribute debe tener :max caracteres como m\\u00e1ximo."}}}',
                'order' => 8,
            ),
            48 =>
            array (
                'id' => 49,
                'data_type_id' => 10,
                'field' => 'direccion',
                'type' => 'text',
                'display_name' => 'Dirección',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":["required","min:2","max:40"],"messages":{"required":"El :attribute es obligatorio.","min":"El :attribute debe tener :min caracteres como m\\u00ednimo.","max":"El :attribute debe tener :max caracteres como m\\u00e1ximo."}}}',
                'order' => 10,
            ),
            49 =>
            array (
                'id' => 50,
                'data_type_id' => 10,
                'field' => 'sexo',
                'type' => 'radio_btn',
                'display_name' => 'Sexo',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"options":{"Masculino":"Masculino","Femenino":"Femenino"},"validation":{"rule":["required"],"messages":{"required":"El :attribute es obligatorio."}}}',
                'order' => 13,
            ),
            50 =>
            array (
                'id' => 51,
                'data_type_id' => 10,
                'field' => 'fecha_de_nacimiento',
                'type' => 'date',
                'display_name' => 'Fecha De Nacimiento',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":["required"],"messages":{"required":"El :attribute es obligatorio."}}}',
                'order' => 14,
            ),
            51 =>
            array (
                'id' => 52,
                'data_type_id' => 10,
                'field' => 'ciudad',
                'type' => 'text',
                'display_name' => 'Ciudad',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":["required","min:2","max:40"],"messages":{"required":"El :attribute es obligatorio.","min":"El :attribute debe tener :min caracteres como m\\u00ednimo.","max":"El :attribute debe tener :max caracteres como m\\u00e1ximo."}}}',
                'order' => 9,
            ),
            52 =>
            array (
                'id' => 53,
                'data_type_id' => 10,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Creado el',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 20,
            ),
            53 =>
            array (
                'id' => 54,
                'data_type_id' => 10,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Actualizado el',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 21,
            ),
            54 =>
            array (
                'id' => 55,
                'data_type_id' => 10,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Eliminado el',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 22,
            ),
            55 =>
            array (
                'id' => 56,
                'data_type_id' => 1,
                'field' => 'email_verified_at',
                'type' => 'timestamp',
                'display_name' => 'Email Verificado',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 6,
            ),
            56 =>
            array (
                'id' => 57,
                'data_type_id' => 1,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Eliminado el',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 13,
            ),
            57 =>
            array (
                'id' => 58,
                'data_type_id' => 11,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            58 =>
            array (
                'id' => 59,
                'data_type_id' => 11,
                'field' => 'user_type',
                'type' => 'text',
                'display_name' => 'User Type',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 2,
            ),
            59 =>
            array (
                'id' => 60,
                'data_type_id' => 11,
                'field' => 'user_id',
                'type' => 'text',
                'display_name' => 'Usuario',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 3,
            ),
            60 =>
            array (
                'id' => 61,
                'data_type_id' => 11,
                'field' => 'event',
                'type' => 'text',
                'display_name' => 'Evento',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 4,
            ),
            61 =>
            array (
                'id' => 62,
                'data_type_id' => 11,
                'field' => 'auditable_type',
                'type' => 'text',
                'display_name' => 'Nombre de Tabla',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 5,
            ),
            62 =>
            array (
                'id' => 63,
                'data_type_id' => 11,
                'field' => 'auditable_id',
                'type' => 'text',
                'display_name' => 'Auditable Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 6,
            ),
            63 =>
            array (
                'id' => 64,
                'data_type_id' => 11,
                'field' => 'old_values',
                'type' => 'text_area',
                'display_name' => 'Datos Antiguos',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 7,
            ),
            64 =>
            array (
                'id' => 65,
                'data_type_id' => 11,
                'field' => 'new_values',
                'type' => 'text_area',
                'display_name' => 'Datos Nuevos',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 8,
            ),
            65 =>
            array (
                'id' => 66,
                'data_type_id' => 11,
                'field' => 'url',
                'type' => 'text',
                'display_name' => 'Url',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 9,
            ),
            66 =>
            array (
                'id' => 67,
                'data_type_id' => 11,
                'field' => 'ip_address',
                'type' => 'text',
                'display_name' => 'Dirección IP',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 10,
            ),
            67 =>
            array (
                'id' => 68,
                'data_type_id' => 11,
                'field' => 'user_agent',
                'type' => 'text',
                'display_name' => 'Navegador Usado',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 11,
            ),
            68 =>
            array (
                'id' => 69,
                'data_type_id' => 11,
                'field' => 'tags',
                'type' => 'text',
                'display_name' => 'Tags',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 12,
            ),
            69 =>
            array (
                'id' => 70,
                'data_type_id' => 11,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Creado el',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 13,
            ),
            70 =>
            array (
                'id' => 71,
                'data_type_id' => 11,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Actualizado el',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 14,
            ),
            71 =>
            array (
                'id' => 72,
                'data_type_id' => 12,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            72 =>
            array (
                'id' => 73,
                'data_type_id' => 12,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Creado el',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 9,
            ),
            73 =>
            array (
                'id' => 74,
                'data_type_id' => 12,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Actualizado el',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 10,
            ),
            74 =>
            array (
                'id' => 75,
                'data_type_id' => 12,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Eliminado el',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 11,
            ),
            75 =>
            array (
                'id' => 76,
                'data_type_id' => 11,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Eliminado el',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 15,
            ),
            76 =>
            array (
                'id' => 77,
                'data_type_id' => 8,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Eliminado el',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 9,
            ),
            77 =>
            array (
                'id' => 78,
                'data_type_id' => 7,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Eliminado el',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 9,
            ),
            78 =>
            array (
                'id' => 79,
                'data_type_id' => 9,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Eliminado el',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 6,
            ),
            79 =>
            array (
                'id' => 80,
                'data_type_id' => 13,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            80 =>
            array (
                'id' => 81,
                'data_type_id' => 13,
                'field' => 'user_id',
                'type' => 'text',
                'display_name' => 'Motivo de Reserva',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 5,
            ),
            81 =>
            array (
                'id' => 82,
                'data_type_id' => 13,
                'field' => 'date',
                'type' => 'date',
                'display_name' => 'Dia',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 9,
            ),
            82 =>
            array (
                'id' => 83,
                'data_type_id' => 13,
                'field' => 'time',
                'type' => 'time',
                'display_name' => 'Hora',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 10,
            ),
            83 =>
            array (
                'id' => 84,
                'data_type_id' => 13,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Creado',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 11,
            ),
            84 =>
            array (
                'id' => 85,
                'data_type_id' => 13,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Actualizado',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 12,
            ),
            85 =>
            array (
                'id' => 86,
                'data_type_id' => 13,
                'field' => 'cita_belongsto_user_relationship',
                'type' => 'relationship',
                'display_name' => 'Doctores',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"scope":"role_id","model":"App\\\\Models\\\\User","table":"users","type":"belongsTo","column":"user_id","key":"id","label":"full_data","pivot_table":"audits","pivot":"0","taggable":"0"}',
                'order' => 6,
            ),
            86 =>
            array (
                'id' => 87,
                'data_type_id' => 13,
                'field' => 'cita_belongsto_paciente_relationship',
                'type' => 'relationship',
                'display_name' => 'Pacientes',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Models\\\\Pacientes","table":"pacientes","type":"belongsTo","column":"paciente_id","key":"id","label":"full_data","pivot_table":"audits","pivot":"0","taggable":"0"}',
                'order' => 8,
            ),
            87 =>
            array (
                'id' => 88,
                'data_type_id' => 13,
                'field' => 'cita_belongsto_servicio_relationship',
                'type' => 'relationship',
                'display_name' => 'Servicios',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Models\\\\Servicios","table":"servicios","type":"belongsTo","column":"servicio_id","key":"id","label":"name","pivot_table":"audits","pivot":"0","taggable":"0"}',
                'order' => 4,
            ),
            88 =>
            array (
                'id' => 89,
                'data_type_id' => 13,
                'field' => 'servicio_id',
                'type' => 'text',
                'display_name' => 'Servicio',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 3,
            ),
            89 =>
            array (
                'id' => 90,
                'data_type_id' => 13,
                'field' => 'motivo',
                'type' => 'text',
                'display_name' => 'Motivo',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 2,
            ),
            90 =>
            array (
                'id' => 91,
                'data_type_id' => 13,
                'field' => 'paciente_id',
                'type' => 'text',
                'display_name' => 'Paciente',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 7,
            ),
            91 =>
            array (
                'id' => 92,
                'data_type_id' => 12,
                'field' => 'day',
                'type' => 'hidden',
                'display_name' => 'Día',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => 'null',
                'order' => 4,
            ),
            92 =>
            array (
                'id' => 93,
                'data_type_id' => 12,
                'field' => 'from',
                'type' => 'time',
                'display_name' => 'Desde',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":"2","id":"custom_id"}}',
                'order' => 5,
            ),
            93 =>
            array (
                'id' => 94,
                'data_type_id' => 12,
                'field' => 'to',
                'type' => 'time',
                'display_name' => 'Hasta',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":"2","id":"custom_id"}}',
                'order' => 6,
            ),
            94 =>
            array (
                'id' => 95,
                'data_type_id' => 12,
                'field' => 'step',
                'type' => 'number',
                'display_name' => 'Intervalo',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":["required","min:1","max:3"],"messages":{"required":"This :attribute field is a must.","max":"This :attribute field maximum :max."}}}',
                'order' => 7,
            ),
            95 =>
            array (
                'id' => 96,
                'data_type_id' => 12,
                'field' => 'off',
                'type' => 'checkbox',
                'display_name' => 'Estado',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"on":"Activado","off":"Desactivado","checked":false}',
                'order' => 8,
            ),
            96 =>
            array (
                'id' => 97,
                'data_type_id' => 12,
                'field' => 'servicio_id',
                'type' => 'text',
                'display_name' => 'Servicio Id',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 3,
            ),
            97 =>
            array (
                'id' => 98,
                'data_type_id' => 12,
                'field' => 'horario_belongsto_servicio_relationship',
                'type' => 'relationship',
                'display_name' => 'Servicio',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Models\\\\Servicios","table":"servicios","type":"belongsTo","column":"servicio_id","key":"id","label":"name","pivot_table":"audits","pivot":"0","taggable":"0"}',
                'order' => 2,
            ),
            98 =>
            array (
                'id' => 99,
                'data_type_id' => 3,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 6,
            ),
            99 =>
            array (
                'id' => 100,
                'data_type_id' => 14,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            100 =>
            array (
                'id' => 101,
                'data_type_id' => 14,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 2,
            ),
            101 =>
            array (
                'id' => 102,
                'data_type_id' => 14,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 3,
            ),
            102 =>
            array (
                'id' => 103,
                'data_type_id' => 10,
                'field' => 'last_name_m',
                'type' => 'text',
                'display_name' => 'Apellido Materno',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":["required","min:3","max:20"],"messages":{"required":"El :attribute es obligatorio.","min":"El :attribute debe tener :min caracteres como m\\u00ednimo.","max":"El :attribute debe tener :max caracteres como m\\u00e1ximo."}}}',
                'order' => 6,
            ),
            103 =>
            array (
                'id' => 104,
                'data_type_id' => 10,
                'field' => 'last_name_c',
                'type' => 'text',
                'display_name' => 'Apellido de Casado',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":["min:3","nullable","max:20"],"messages":{"min":"El :attribute debe tener :min caracteres como m\\u00ednimo.","max":"El :attribute debe tener :max caracteres como m\\u00e1ximo."}}}',
                'order' => 7,
            ),
            104 =>
            array (
                'id' => 105,
                'data_type_id' => 10,
                'field' => 'barrio',
                'type' => 'text',
                'display_name' => 'Barrio',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":["nullable","min:3","max:40"],"messages":{"min":"El :attribute debe tener :min caracteres como m\\u00ednimo.","max":"El :attribute debe tener :max caracteres como m\\u00e1ximo."}}}',
                'order' => 11,
            ),
            105 =>
            array (
                'id' => 106,
                'data_type_id' => 10,
                'field' => 'ocupacion',
                'type' => 'text',
                'display_name' => 'Ocupación',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":["nullable","min:3","max:40"],"messages":{"min":"El :attribute debe tener :min caracteres como m\\u00ednimo.","max":"El :attribute debe tener :max caracteres como m\\u00e1ximo."}}}',
                'order' => 15,
            ),
            106 =>
            array (
                'id' => 107,
                'data_type_id' => 10,
                'field' => 'grado',
                'type' => 'text',
                'display_name' => 'Grado de Escolaridad',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":["nullable","min:3","max:40"],"messages":{"min":"El :attribute debe tener :min caracteres como m\\u00ednimo.","max":"El :attribute debe tener :max caracteres como m\\u00e1ximo."}}}',
                'order' => 16,
            ),
            107 =>
            array (
                'id' => 108,
                'data_type_id' => 10,
                'field' => 'edad',
                'type' => 'text',
                'display_name' => 'Edad',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":["required","min:1","max:3"],"messages":{"required":"El :attribute es obligatorio.","min":"El :attribute debe tener :min caracteres como m\\u00ednimo.","max":"El :attribute debe tener :max caracteres como m\\u00e1ximo."}}}',
                'order' => 17,
            ),
            108 =>
            array (
                'id' => 109,
                'data_type_id' => 10,
                'field' => 'referido',
                'type' => 'text',
                'display_name' => 'Referido',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":["nullable","min:3","max:40"],"messages":{"min":"El :attribute debe tener :min caracteres como m\\u00ednimo.","max":"El :attribute debe tener :max caracteres como m\\u00e1ximo."}}}',
                'order' => 18,
            ),
            109 =>
            array (
                'id' => 110,
                'data_type_id' => 10,
                'field' => 'familiar',
                'type' => 'text',
                'display_name' => 'Familiar Auxiliar',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":["nullable","min:3","max:40"],"messages":{"min":"El :attribute debe tener :min caracteres como m\\u00ednimo.","max":"El :attribute debe tener :max caracteres como m\\u00e1ximo."}}}',
                'order' => 19,
            ),
            110 =>
            array (
                'id' => 111,
                'data_type_id' => 10,
                'field' => 'documento',
                'type' => 'text',
                'display_name' => 'Documento',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":["required","min:5","max:15"],"messages":{"required":"El :attribute es obligatorio.","min":"El :attribute debe tener :min caracteres como m\\u00ednimo.","max":"El :attribute debe tener :min caracteres como m\\u00ednimo."}}}',
                'order' => 3,
            ),
            111 =>
            array (
                'id' => 112,
                'data_type_id' => 10,
                'field' => 'tipo_documento',
                'type' => 'radio_btn',
                'display_name' => 'Tipo de Documento',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"default":"Carnet de Identidad","options":{"Carnet de Identidad":"Carnet de Identidad","Pasaporte":"Pasaporte"},"validation":{"rule":["required"],"messages":{"required":"El :attribute es obligatorio."}}}',
                'order' => 2,
            ),
            112 =>
            array (
                'id' => 113,
                'data_type_id' => 10,
                'field' => 'celular',
                'type' => 'number',
                'display_name' => 'Celular',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":["nullable","min:5","max:15"],"messages":{"min":"El :attribute debe tener :min caracteres como m\\u00ednimo.","max":"El :attribute debe tener :max caracteres como m\\u00e1ximo."}}}',
                'order' => 12,
            ),
            113 =>
            array (
                'id' => 114,
                'data_type_id' => 16,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            114 =>
            array (
                'id' => 115,
                'data_type_id' => 16,
                'field' => 'motivo',
                'type' => 'text',
                'display_name' => 'Motivo',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 2,
            ),
            115 =>
            array (
                'id' => 116,
                'data_type_id' => 16,
                'field' => 'enfermedad',
                'type' => 'text',
                'display_name' => 'Enfermedad',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 3,
            ),
            116 =>
            array (
                'id' => 117,
                'data_type_id' => 16,
                'field' => 'diagnostico',
                'type' => 'text',
                'display_name' => 'Diagnóstico',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 4,
            ),
            117 =>
            array (
                'id' => 118,
                'data_type_id' => 16,
                'field' => 'conducta',
                'type' => 'text',
                'display_name' => 'Conducta',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 5,
            ),
            118 =>
            array (
                'id' => 119,
                'data_type_id' => 16,
                'field' => 'tratamiento',
                'type' => 'text',
                'display_name' => 'Tratamiento',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 6,
            ),
            119 =>
            array (
                'id' => 120,
                'data_type_id' => 16,
                'field' => 'citas_id',
                'type' => 'text',
                'display_name' => 'Citas Id',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 7,
            ),
            120 =>
            array (
                'id' => 121,
                'data_type_id' => 16,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Eliminado el',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 10,
            ),
            121 =>
            array (
                'id' => 122,
                'data_type_id' => 16,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Creado el',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 8,
            ),
            122 =>
            array (
                'id' => 123,
                'data_type_id' => 16,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Actualizado el',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 9,
            ),
        ));


    }
}
