<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PacientesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('pacientes')->delete();
        
        \DB::table('pacientes')->insert(array (
            0 => 
            array (
                'ciudad' => 'Oruro',
                'created_at' => '2023-07-14 19:47:26',
                'deleted_at' => NULL,
                'direccion' => 'Paseo Jáquez, 892, Ático 6º',
                'email' => 'campos.nadia@example.net',
                'fecha_de_nacimiento' => '1999-05-11 ',
                'id' => 1,
                'last_name' => 'Moreno',
                'name' => 'Paula Córdova',
                'sexo' => 'Femenino',
                'updated_at' => '2023-07-14 19:47:26',
            ),
            1 => 
            array (
                'ciudad' => 'La Paz',
                'created_at' => '2023-07-14 19:47:26',
                'deleted_at' => NULL,
                'direccion' => 'Paseo Menchaca, 29, 5º A',
                'email' => 'miriam70@example.org',
                'fecha_de_nacimiento' => '1975-10-18 ',
                'id' => 2,
                'last_name' => 'Ordoñez',
                'name' => 'Gonzalo Garibay Segundo',
                'sexo' => 'Masculino',
                'updated_at' => '2023-07-14 19:47:26',
            ),
            2 => 
            array (
                'ciudad' => 'La Paz',
                'created_at' => '2023-07-14 19:47:26',
                'deleted_at' => NULL,
                'direccion' => 'Camino Tórrez, 792, 47º E',
                'email' => 'gerard.covarrubias@example.com',
                'fecha_de_nacimiento' => '1982-09-24 ',
                'id' => 3,
                'last_name' => 'Ortíz',
                'name' => 'Iván Ceja',
                'sexo' => 'Masculino',
                'updated_at' => '2023-07-14 19:47:26',
            ),
            3 => 
            array (
                'ciudad' => 'Santa Cruz',
                'created_at' => '2023-07-14 19:47:26',
                'deleted_at' => NULL,
                'direccion' => 'Rúa Nayara, 8, 4º C',
                'email' => 'anaisabel91@example.org',
                'fecha_de_nacimiento' => '2018-10-06 ',
                'id' => 4,
                'last_name' => 'Zúñiga',
                'name' => 'Diana Mascareñas',
                'sexo' => 'Femenino',
                'updated_at' => '2023-07-14 19:47:26',
            ),
            4 => 
            array (
                'ciudad' => 'La Paz',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Carrer Alvarado, 7, 9º 1º',
                'email' => 'tafoya.alex@example.org',
                'fecha_de_nacimiento' => '2010-09-11 ',
                'id' => 5,
                'last_name' => 'Barrios',
                'name' => 'María Ángeles Millán',
                'sexo' => 'Masculino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            5 => 
            array (
                'ciudad' => 'Santa Cruz',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Paseo Raúl, 476, 86º A',
                'email' => 'xsaldana@example.net',
                'fecha_de_nacimiento' => '2023-01-08 ',
                'id' => 6,
                'last_name' => 'Escobedo',
                'name' => 'Dr. Miriam Véliz Segundo',
                'sexo' => 'Femenino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            6 => 
            array (
                'ciudad' => 'Oruro',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Plaza Ruiz, 5, 98º 4º',
                'email' => 'roberto.serna@example.com',
                'fecha_de_nacimiento' => '2004-02-12 ',
                'id' => 7,
                'last_name' => 'Altamirano',
                'name' => 'Rubén Montez',
                'sexo' => 'Masculino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            7 => 
            array (
                'ciudad' => 'Santa Cruz',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Camiño Alexandra, 963, 22º A',
                'email' => 'cardenas.olivia@example.org',
                'fecha_de_nacimiento' => '2013-03-08 ',
                'id' => 8,
                'last_name' => 'Valladares',
                'name' => 'Ismael Garica',
                'sexo' => 'Masculino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            8 => 
            array (
                'ciudad' => 'Santa Cruz',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Calle Laureano, 5, Bajo 2º',
                'email' => 'avila.ainara@example.org',
                'fecha_de_nacimiento' => '2009-12-12 ',
                'id' => 9,
                'last_name' => 'Rodarte',
                'name' => 'Dr. Alex Mora Segundo',
                'sexo' => 'Femenino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            9 => 
            array (
                'ciudad' => 'La Paz',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Paseo Aleix, 6, Bajo 4º',
                'email' => 'olivia.lugo@example.org',
                'fecha_de_nacimiento' => '2005-02-11 ',
                'id' => 10,
                'last_name' => 'Bueno',
                'name' => 'Alejandro Bahena Segundo',
                'sexo' => 'Femenino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            10 => 
            array (
                'ciudad' => 'La Paz',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Rúa Sofía, 532, 32º A',
                'email' => 'pablo.barrientos@example.com',
                'fecha_de_nacimiento' => '2008-11-15 ',
                'id' => 11,
                'last_name' => 'Hidalgo',
                'name' => 'Noelia Martínez Hijo',
                'sexo' => 'Femenino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            11 => 
            array (
                'ciudad' => 'Santa Cruz',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Calle Helena, 77, 23º 3º',
                'email' => 'pilar14@example.net',
                'fecha_de_nacimiento' => '2015-02-09 ',
                'id' => 12,
                'last_name' => 'Dávila',
                'name' => 'Margarita Crespo Segundo',
                'sexo' => 'Masculino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            12 => 
            array (
                'ciudad' => 'Santa Cruz',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Calle Luisa, 4, Ático 8º',
                'email' => 'sserrano@example.org',
                'fecha_de_nacimiento' => '2005-11-18 ',
                'id' => 13,
                'last_name' => 'Juárez',
                'name' => 'Isaac Parra',
                'sexo' => 'Masculino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            13 => 
            array (
                'ciudad' => 'Santa Cruz',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Plaza Clara, 97, 8º C',
                'email' => 'enrique.canales@example.net',
                'fecha_de_nacimiento' => '1979-02-16 ',
                'id' => 14,
                'last_name' => 'Solano',
                'name' => 'Enrique Alfonso',
                'sexo' => 'Femenino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            14 => 
            array (
                'ciudad' => 'La Paz',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Plaza Córdoba, 37, 6º C',
                'email' => 'izan08@example.com',
                'fecha_de_nacimiento' => '2017-01-11 ',
                'id' => 15,
                'last_name' => 'Garica',
                'name' => 'Srta. Esther Peres Tercero',
                'sexo' => 'Femenino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            15 => 
            array (
                'ciudad' => 'La Paz',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Rúa Benito, 2, Ático 4º',
                'email' => 'vila.carmen@example.org',
                'fecha_de_nacimiento' => '1998-12-26 ',
                'id' => 16,
                'last_name' => 'Aponte',
                'name' => 'Antonia Soto Segundo',
                'sexo' => 'Masculino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            16 => 
            array (
                'ciudad' => 'La Paz',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Plaza Escamilla, 6, 4º E',
                'email' => 'domingo.lorena@example.org',
                'fecha_de_nacimiento' => '1976-06-29 ',
                'id' => 17,
                'last_name' => 'Roca',
                'name' => 'Fátima Pedroza',
                'sexo' => 'Femenino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            17 => 
            array (
                'ciudad' => 'Santa Cruz',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Praza Esther, 7, 3º',
                'email' => 'luna25@example.com',
                'fecha_de_nacimiento' => '1982-06-02 ',
                'id' => 18,
                'last_name' => 'Villa',
                'name' => 'Alejandro Muñoz',
                'sexo' => 'Masculino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            18 => 
            array (
                'ciudad' => 'Santa Cruz',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Plaça Carrasco, 938, 6º B',
                'email' => 'bmeraz@example.org',
                'fecha_de_nacimiento' => '2000-12-06 ',
                'id' => 19,
                'last_name' => 'Armas',
                'name' => 'Luisa Gálvez',
                'sexo' => 'Masculino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            19 => 
            array (
                'ciudad' => 'Oruro',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Calle Carla, 89, 0º D',
                'email' => 'ovarela@example.com',
                'fecha_de_nacimiento' => '1981-12-19 ',
                'id' => 20,
                'last_name' => 'Rivero',
                'name' => 'Dña Carmen Vallejo Hijo',
                'sexo' => 'Femenino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            20 => 
            array (
                'ciudad' => 'La Paz',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Camino Costa, 82, 45º A',
                'email' => 'nora87@example.net',
                'fecha_de_nacimiento' => '1986-03-22 ',
                'id' => 21,
                'last_name' => 'Villarreal',
                'name' => 'Dña Zoe Alcántar',
                'sexo' => 'Femenino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            21 => 
            array (
                'ciudad' => 'La Paz',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Travessera Bahena, 1, Bajo 9º',
                'email' => 'hgalvez@example.com',
                'fecha_de_nacimiento' => '2012-06-04 ',
                'id' => 22,
                'last_name' => 'Castellano',
                'name' => 'Ing. Marco Cuellar Tercero',
                'sexo' => 'Masculino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            22 => 
            array (
                'ciudad' => 'Santa Cruz',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Camiño Guerra, 584, 7º F',
                'email' => 'fernandez.miguel@example.org',
                'fecha_de_nacimiento' => '2006-02-15 ',
                'id' => 23,
                'last_name' => 'Ramos',
                'name' => 'Guillem Delacrúz',
                'sexo' => 'Masculino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            23 => 
            array (
                'ciudad' => 'Santa Cruz',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Paseo Isabel, 882, 1º C',
                'email' => 'jose.guajardo@example.net',
                'fecha_de_nacimiento' => '1981-09-22 ',
                'id' => 24,
                'last_name' => 'Reynoso',
                'name' => 'Martina Grijalva',
                'sexo' => 'Femenino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            24 => 
            array (
                'ciudad' => 'Santa Cruz',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Praza Calvillo, 4, 7º B',
                'email' => 'yfarias@example.org',
                'fecha_de_nacimiento' => '1975-04-04 ',
                'id' => 25,
                'last_name' => 'Ureña',
                'name' => 'Margarita Luque',
                'sexo' => 'Masculino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            25 => 
            array (
                'ciudad' => 'La Paz',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Carrer Margarita, 402, 17º A',
                'email' => 'hernadez.ariadna@example.net',
                'fecha_de_nacimiento' => '1979-06-20 ',
                'id' => 26,
                'last_name' => 'Sancho',
                'name' => 'Ing. Carlota Arias',
                'sexo' => 'Masculino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            26 => 
            array (
                'ciudad' => 'La Paz',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Ruela Rosario, 55, 89º B',
                'email' => 'ncolon@example.net',
                'fecha_de_nacimiento' => '1989-08-04 ',
                'id' => 27,
                'last_name' => 'Juan',
                'name' => 'Teresa Vázquez',
                'sexo' => 'Masculino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            27 => 
            array (
                'ciudad' => 'Santa Cruz',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Calle Sevilla, 30, 2º C',
                'email' => 'rocio.arteaga@example.net',
                'fecha_de_nacimiento' => '1987-08-15 ',
                'id' => 28,
                'last_name' => 'Olivares',
                'name' => 'Leire Cerda',
                'sexo' => 'Masculino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            28 => 
            array (
                'ciudad' => 'Oruro',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Ruela Jesús, 71, 3º B',
                'email' => 'mariacarmen.valverde@example.net',
                'fecha_de_nacimiento' => '2014-12-03 ',
                'id' => 29,
                'last_name' => 'Soto',
                'name' => 'Marina Rodarte Tercero',
                'sexo' => 'Femenino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            29 => 
            array (
                'ciudad' => 'Oruro',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Ronda Cabello, 1, 8º F',
                'email' => 'carla.tapia@example.com',
                'fecha_de_nacimiento' => '2019-05-08 ',
                'id' => 30,
                'last_name' => 'Baca',
                'name' => 'Manuela Luna',
                'sexo' => 'Femenino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            30 => 
            array (
                'ciudad' => 'Santa Cruz',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Passeig Llorente, 355, 05º D',
                'email' => 'carlos63@example.org',
                'fecha_de_nacimiento' => '2016-01-24 ',
                'id' => 31,
                'last_name' => 'Arellano',
                'name' => 'Samuel Montalvo',
                'sexo' => 'Masculino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            31 => 
            array (
                'ciudad' => 'Oruro',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Carrer Vega, 8, Bajos',
                'email' => 'carbajal.olivia@example.net',
                'fecha_de_nacimiento' => '2009-03-21 ',
                'id' => 32,
                'last_name' => 'Guillen',
                'name' => 'Isaac Bermúdez',
                'sexo' => 'Femenino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            32 => 
            array (
                'ciudad' => 'La Paz',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Carrer Yaiza, 57, 0º A',
                'email' => 'dmanzano@example.com',
                'fecha_de_nacimiento' => '2013-07-24 ',
                'id' => 33,
                'last_name' => 'Arroyo',
                'name' => 'Dr. Olga Juan',
                'sexo' => 'Masculino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            33 => 
            array (
                'ciudad' => 'La Paz',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Ruela Alaniz, 4, 98º A',
                'email' => 'miguel.guillem@example.net',
                'fecha_de_nacimiento' => '1986-07-17 ',
                'id' => 34,
                'last_name' => 'Treviño',
                'name' => 'Andrés Haro',
                'sexo' => 'Femenino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            34 => 
            array (
                'ciudad' => 'Santa Cruz',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Ruela Laura, 276, 76º B',
                'email' => 'leyva.malak@example.net',
                'fecha_de_nacimiento' => '1975-02-23 ',
                'id' => 35,
                'last_name' => 'Serna',
                'name' => 'Dr. Jesús Morán',
                'sexo' => 'Masculino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            35 => 
            array (
                'ciudad' => 'Oruro',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Rúa Diana, 837, 22º B',
                'email' => 'moran.yaiza@example.net',
                'fecha_de_nacimiento' => '2012-05-21 ',
                'id' => 36,
                'last_name' => 'Munguía',
                'name' => 'Ing. Rafael Preciado',
                'sexo' => 'Masculino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            36 => 
            array (
                'ciudad' => 'La Paz',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Plaça Mar, 81, 0º D',
                'email' => 'vmelgar@example.net',
                'fecha_de_nacimiento' => '1991-11-11 ',
                'id' => 37,
                'last_name' => 'Rico',
                'name' => 'Oliver Lomeli',
                'sexo' => 'Femenino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            37 => 
            array (
                'ciudad' => 'La Paz',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Plaça Alonso, 196, 66º D',
                'email' => 'udeleon@example.net',
                'fecha_de_nacimiento' => '2001-03-09 ',
                'id' => 38,
                'last_name' => 'Ávila',
                'name' => 'Marcos Expósito',
                'sexo' => 'Femenino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            38 => 
            array (
                'ciudad' => 'La Paz',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Rúa Zoe, 5, 69º D',
                'email' => 'carmen.guevara@example.com',
                'fecha_de_nacimiento' => '1995-10-11 ',
                'id' => 39,
                'last_name' => 'Arredondo',
                'name' => 'Silvia Luevano',
                'sexo' => 'Femenino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            39 => 
            array (
                'ciudad' => 'Santa Cruz',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Travessera Gabriela, 76, Ático 2º',
                'email' => 'grijalva.martina@example.net',
                'fecha_de_nacimiento' => '1970-08-01 ',
                'id' => 40,
                'last_name' => 'Saldivar',
                'name' => 'Srta. Ángeles Burgos Tercero',
                'sexo' => 'Femenino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            40 => 
            array (
                'ciudad' => 'Santa Cruz',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Plaça Aitana, 6, Bajos',
                'email' => 'cristian.manzano@example.com',
                'fecha_de_nacimiento' => '2022-12-25 ',
                'id' => 41,
                'last_name' => 'Solorio',
                'name' => 'Martín Amaya',
                'sexo' => 'Masculino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            41 => 
            array (
                'ciudad' => 'Oruro',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Plaza López, 11, Ático 9º',
                'email' => 'nmatos@example.net',
                'fecha_de_nacimiento' => '2013-07-01 ',
                'id' => 42,
                'last_name' => 'Marrero',
                'name' => 'Lic. Ona Esquibel',
                'sexo' => 'Masculino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            42 => 
            array (
                'ciudad' => 'Oruro',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Travesía Carrasco, 2, Ático 8º',
                'email' => 'david.garibay@example.net',
                'fecha_de_nacimiento' => '2014-03-13 ',
                'id' => 43,
                'last_name' => 'Murillo',
                'name' => 'Alex Romo',
                'sexo' => 'Femenino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            43 => 
            array (
                'ciudad' => 'La Paz',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Paseo Hugo, 9, 9º C',
                'email' => 'pelayo.natalia@example.net',
                'fecha_de_nacimiento' => '1981-09-15 ',
                'id' => 44,
                'last_name' => 'Rosas',
                'name' => 'Clara Arevalo',
                'sexo' => 'Femenino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            44 => 
            array (
                'ciudad' => 'Santa Cruz',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Avenida Preciado, 72, Ático 2º',
                'email' => 'jordi50@example.org',
                'fecha_de_nacimiento' => '1980-10-30 ',
                'id' => 45,
                'last_name' => 'Paredes',
                'name' => 'Srta. Nayara Santacruz Hijo',
                'sexo' => 'Masculino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            45 => 
            array (
                'ciudad' => 'Santa Cruz',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Calle Otero, 524, 44º F',
                'email' => 'xsoler@example.org',
                'fecha_de_nacimiento' => '2002-05-02 ',
                'id' => 46,
                'last_name' => 'Rodríguez',
                'name' => 'Ing. Nadia Ontiveros Hijo',
                'sexo' => 'Femenino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            46 => 
            array (
                'ciudad' => 'Santa Cruz',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Avenida Rentería, 42, 0º A',
                'email' => 'izan.adame@example.org',
                'fecha_de_nacimiento' => '2019-07-10 ',
                'id' => 47,
                'last_name' => 'Puente',
                'name' => 'Valentina Centeno',
                'sexo' => 'Femenino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            47 => 
            array (
                'ciudad' => 'Oruro',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Calle Juan, 33, Bajos',
                'email' => 'irene.enriquez@example.org',
                'fecha_de_nacimiento' => '1978-12-01 ',
                'id' => 48,
                'last_name' => 'Betancourt',
                'name' => 'Asier Urrutia',
                'sexo' => 'Femenino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            48 => 
            array (
                'ciudad' => 'La Paz',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Carrer Lucas, 3, Bajo 5º',
                'email' => 'alejandra38@example.com',
                'fecha_de_nacimiento' => '1973-07-05 ',
                'id' => 49,
                'last_name' => 'Saiz',
                'name' => 'Ing. Blanca Barrera Tercero',
                'sexo' => 'Masculino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            49 => 
            array (
                'ciudad' => 'Santa Cruz',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Plaza Adame, 600, 17º E',
                'email' => 'xmontero@example.org',
                'fecha_de_nacimiento' => '2000-07-18 ',
                'id' => 50,
                'last_name' => 'Medrano',
                'name' => 'Jesús Mares',
                'sexo' => 'Femenino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            50 => 
            array (
                'ciudad' => 'Oruro',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Ruela Soler, 20, 7º A',
                'email' => 'gabriel.carrasquillo@example.net',
                'fecha_de_nacimiento' => '2019-02-28 ',
                'id' => 51,
                'last_name' => 'Delapaz',
                'name' => 'Carolina Arriaga',
                'sexo' => 'Masculino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            51 => 
            array (
                'ciudad' => 'Santa Cruz',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Carrer Muñoz, 472, Ático 8º',
                'email' => 'blanco.carolina@example.org',
                'fecha_de_nacimiento' => '1983-01-23 ',
                'id' => 52,
                'last_name' => 'Salazar',
                'name' => 'Guillem Amador',
                'sexo' => 'Femenino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            52 => 
            array (
                'ciudad' => 'Oruro',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Travesía Bermúdez, 74, 36º A',
                'email' => 'cervantez.javier@example.org',
                'fecha_de_nacimiento' => '1974-06-02 ',
                'id' => 53,
                'last_name' => 'Giménez',
                'name' => 'Pablo Naranjo',
                'sexo' => 'Femenino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            53 => 
            array (
                'ciudad' => 'Oruro',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Ronda Del Río, 986, Ático 5º',
                'email' => 'vhuerta@example.org',
                'fecha_de_nacimiento' => '2020-09-18 ',
                'id' => 54,
                'last_name' => 'Delrío',
                'name' => 'Isabel Almaráz',
                'sexo' => 'Femenino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            54 => 
            array (
                'ciudad' => 'La Paz',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Passeig Martí, 51, 1º D',
                'email' => 'silva.claudia@example.net',
                'fecha_de_nacimiento' => '1997-07-28 ',
                'id' => 55,
                'last_name' => 'Del Río',
                'name' => 'Víctor Ordóñez',
                'sexo' => 'Masculino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            55 => 
            array (
                'ciudad' => 'Santa Cruz',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Plaça Joel, 72, 9º B',
                'email' => 'silvia.roybal@example.org',
                'fecha_de_nacimiento' => '1980-07-29 ',
                'id' => 56,
                'last_name' => 'Orozco',
                'name' => 'Fernando Barrientos Hijo',
                'sexo' => 'Masculino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            56 => 
            array (
                'ciudad' => 'La Paz',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Ruela Roybal, 4, 3º',
                'email' => 'esther.palacios@example.net',
                'fecha_de_nacimiento' => '1996-10-15 ',
                'id' => 57,
                'last_name' => 'Roig',
                'name' => 'D. Marc Guzmán',
                'sexo' => 'Femenino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            57 => 
            array (
                'ciudad' => 'Oruro',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Paseo Almonte, 45, 92º C',
                'email' => 'concepcion.gabriela@example.org',
                'fecha_de_nacimiento' => '2000-12-20 ',
                'id' => 58,
                'last_name' => 'Heredia',
                'name' => 'Ariadna Zelaya',
                'sexo' => 'Femenino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            58 => 
            array (
                'ciudad' => 'La Paz',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Praza Berta, 262, Bajo 1º',
                'email' => 'zduenas@example.org',
                'fecha_de_nacimiento' => '1973-09-15 ',
                'id' => 59,
                'last_name' => 'Ávila',
                'name' => 'Aitana Benavides',
                'sexo' => 'Masculino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            59 => 
            array (
                'ciudad' => 'La Paz',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Avinguda Iker, 57, 4º D',
                'email' => 'antonia.ornelas@example.com',
                'fecha_de_nacimiento' => '1999-12-04 ',
                'id' => 60,
                'last_name' => 'Martos',
                'name' => 'Sr. Lucas Soto',
                'sexo' => 'Femenino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            60 => 
            array (
                'ciudad' => 'La Paz',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Ruela Espinoza, 3, 0º D',
                'email' => 'dario84@example.org',
                'fecha_de_nacimiento' => '2002-02-22 ',
                'id' => 61,
                'last_name' => 'Lucio',
                'name' => 'Dr. Mar Fuentes',
                'sexo' => 'Masculino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            61 => 
            array (
                'ciudad' => 'La Paz',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Plaza Garica, 74, 2º D',
                'email' => 'guevara.alba@example.net',
                'fecha_de_nacimiento' => '1970-12-06 ',
                'id' => 62,
                'last_name' => 'Villagómez',
                'name' => 'Aina Roybal',
                'sexo' => 'Masculino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            62 => 
            array (
                'ciudad' => 'Santa Cruz',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Carrer Ontiveros, 836, 42º 9º',
                'email' => 'izquierdo.alonso@example.com',
                'fecha_de_nacimiento' => '2012-08-23 ',
                'id' => 63,
                'last_name' => 'Villar',
                'name' => 'Verónica Jurado',
                'sexo' => 'Masculino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            63 => 
            array (
                'ciudad' => 'La Paz',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Camino Mireles, 3, Ático 9º',
                'email' => 'anaisabel.delatorre@example.net',
                'fecha_de_nacimiento' => '2001-02-07 ',
                'id' => 64,
                'last_name' => 'Caballero',
                'name' => 'Omar Acevedo',
                'sexo' => 'Masculino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            64 => 
            array (
                'ciudad' => 'La Paz',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Ronda Castañeda, 468, 0º E',
                'email' => 'mar.maya@example.net',
                'fecha_de_nacimiento' => '2005-02-15 ',
                'id' => 65,
                'last_name' => 'Ferrer',
                'name' => 'Paula Almonte Hijo',
                'sexo' => 'Masculino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            65 => 
            array (
                'ciudad' => 'Oruro',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Plaza Cristian, 6, 45º E',
                'email' => 'gloria.rey@example.net',
                'fecha_de_nacimiento' => '1974-02-13 ',
                'id' => 66,
                'last_name' => 'Cruz',
                'name' => 'Ing. Amparo Acosta Segundo',
                'sexo' => 'Femenino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            66 => 
            array (
                'ciudad' => 'La Paz',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Avenida Vergara, 58, Entre suelo 4º',
                'email' => 'baca.enrique@example.com',
                'fecha_de_nacimiento' => '1990-08-28 ',
                'id' => 67,
                'last_name' => 'Simón',
                'name' => 'Dr. Marcos Arribas',
                'sexo' => 'Femenino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            67 => 
            array (
                'ciudad' => 'La Paz',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Avenida Isabel, 321, Ático 6º',
                'email' => 'santiago69@example.com',
                'fecha_de_nacimiento' => '1986-01-18 ',
                'id' => 68,
                'last_name' => 'Guardado',
                'name' => 'Lic. Biel Pineda',
                'sexo' => 'Masculino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            68 => 
            array (
                'ciudad' => 'Santa Cruz',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Carrer Yeray, 454, Bajos',
                'email' => 'javier.lomeli@example.org',
                'fecha_de_nacimiento' => '2007-04-21 ',
                'id' => 69,
                'last_name' => 'Lovato',
                'name' => 'Alicia Guzmán Hijo',
                'sexo' => 'Masculino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            69 => 
            array (
                'ciudad' => 'Oruro',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Travessera Avilés, 403, Ático 2º',
                'email' => 'ainhoa23@example.org',
                'fecha_de_nacimiento' => '1975-12-09 ',
                'id' => 70,
                'last_name' => 'Murillo',
                'name' => 'Alejandro Segovia',
                'sexo' => 'Masculino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            70 => 
            array (
                'ciudad' => 'Oruro',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Travessera Guillermo, 982, 6º F',
                'email' => 'anaisabel.navarrete@example.com',
                'fecha_de_nacimiento' => '2002-07-04 ',
                'id' => 71,
                'last_name' => 'Galarza',
                'name' => 'Ing. Daniela Aponte',
                'sexo' => 'Femenino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            71 => 
            array (
                'ciudad' => 'Santa Cruz',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Paseo Escobar, 1, 4º 1º',
                'email' => 'jon21@example.net',
                'fecha_de_nacimiento' => '1994-07-20 ',
                'id' => 72,
                'last_name' => 'Alcaráz',
                'name' => 'Ing. Rodrigo Perales',
                'sexo' => 'Masculino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            72 => 
            array (
                'ciudad' => 'Oruro',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Passeig Yaiza, 3, 4º',
                'email' => 'lozada.leire@example.org',
                'fecha_de_nacimiento' => '2021-09-13 ',
                'id' => 73,
                'last_name' => 'Bernal',
                'name' => 'Sra. Marina Quiñones',
                'sexo' => 'Masculino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            73 => 
            array (
                'ciudad' => 'Santa Cruz',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Calle Juan, 71, 45º 9º',
                'email' => 'lugo.cesar@example.org',
                'fecha_de_nacimiento' => '1995-03-06 ',
                'id' => 74,
                'last_name' => 'Ceballos',
                'name' => 'Luis Pelayo',
                'sexo' => 'Femenino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            74 => 
            array (
                'ciudad' => 'La Paz',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Plaça Patricia, 3, 7º F',
                'email' => 'hsantos@example.org',
                'fecha_de_nacimiento' => '1981-09-09 ',
                'id' => 75,
                'last_name' => 'Calvo',
                'name' => 'María Dolores Porras',
                'sexo' => 'Femenino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            75 => 
            array (
                'ciudad' => 'Oruro',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Camiño Sofía, 306, Bajos',
                'email' => 'cesar76@example.net',
                'fecha_de_nacimiento' => '2013-07-30 ',
                'id' => 76,
                'last_name' => 'Ballesteros',
                'name' => 'Ing. Izan Negrón',
                'sexo' => 'Femenino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            76 => 
            array (
                'ciudad' => 'Santa Cruz',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Passeig Luisa, 52, 5º',
                'email' => 'africa55@example.com',
                'fecha_de_nacimiento' => '1974-07-03 ',
                'id' => 77,
                'last_name' => 'Soliz',
                'name' => 'Sra. Pau Casillas Tercero',
                'sexo' => 'Masculino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            77 => 
            array (
                'ciudad' => 'La Paz',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Ruela Naranjo, 3, 3º A',
                'email' => 'claudia.santillan@example.com',
                'fecha_de_nacimiento' => '1988-09-15 ',
                'id' => 78,
                'last_name' => 'Yáñez',
                'name' => 'Ana Zamudio',
                'sexo' => 'Masculino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            78 => 
            array (
                'ciudad' => 'Oruro',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Travesía Ángel, 2, Ático 5º',
                'email' => 'padron.oriol@example.com',
                'fecha_de_nacimiento' => '1999-09-22 ',
                'id' => 79,
                'last_name' => 'Blanco',
                'name' => 'Julia Orellana',
                'sexo' => 'Femenino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            79 => 
            array (
                'ciudad' => 'Oruro',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Calle Coronado, 7, 4º C',
                'email' => 'tpuente@example.org',
                'fecha_de_nacimiento' => '2015-05-18 ',
                'id' => 80,
                'last_name' => 'Rico',
                'name' => 'Rocío Delapaz',
                'sexo' => 'Femenino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            80 => 
            array (
                'ciudad' => 'Oruro',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Avinguda Nora, 4, 94º A',
                'email' => 'ltijerina@example.org',
                'fecha_de_nacimiento' => '1974-01-19 ',
                'id' => 81,
                'last_name' => 'Acosta',
                'name' => 'Dña Sandra De la Torre',
                'sexo' => 'Femenino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            81 => 
            array (
                'ciudad' => 'Oruro',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Travessera Osorio, 78, 53º A',
                'email' => 'omar50@example.org',
                'fecha_de_nacimiento' => '1992-09-02 ',
                'id' => 82,
                'last_name' => 'Enríquez',
                'name' => 'Biel Cano',
                'sexo' => 'Femenino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            82 => 
            array (
                'ciudad' => 'La Paz',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Travesía Francisco, 1, 0º D',
                'email' => 'abreu.mireia@example.com',
                'fecha_de_nacimiento' => '1973-10-07 ',
                'id' => 83,
                'last_name' => 'Rodrigo',
                'name' => 'Ing. Iván Pelayo Hijo',
                'sexo' => 'Masculino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            83 => 
            array (
                'ciudad' => 'Santa Cruz',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Camino Ismael, 419, 3º',
                'email' => 'angel29@example.org',
                'fecha_de_nacimiento' => '1971-12-04 ',
                'id' => 84,
                'last_name' => 'Maestas',
                'name' => 'Dr. Gonzalo Holguín Segundo',
                'sexo' => 'Femenino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            84 => 
            array (
                'ciudad' => 'Santa Cruz',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Paseo Vega, 557, 6º C',
                'email' => 'guillem66@example.net',
                'fecha_de_nacimiento' => '1992-07-21 ',
                'id' => 85,
                'last_name' => 'Valles',
                'name' => 'Sr. José Manuel Pabón Hijo',
                'sexo' => 'Masculino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            85 => 
            array (
                'ciudad' => 'Santa Cruz',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Rúa Ruíz, 357, 27º B',
                'email' => 'guillermo.feliciano@example.net',
                'fecha_de_nacimiento' => '2015-03-23 ',
                'id' => 86,
                'last_name' => 'Rincón',
                'name' => 'Lic. Roberto Briseño Tercero',
                'sexo' => 'Femenino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            86 => 
            array (
                'ciudad' => 'Oruro',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Passeig Sola, 51, 8º F',
                'email' => 'dmartin@example.com',
                'fecha_de_nacimiento' => '1989-12-21 ',
                'id' => 87,
                'last_name' => 'Dávila',
                'name' => 'Dr. Claudia Griego',
                'sexo' => 'Femenino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            87 => 
            array (
                'ciudad' => 'Santa Cruz',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Camiño Sedillo, 118, 55º B',
                'email' => 'lmejia@example.com',
                'fecha_de_nacimiento' => '1997-11-16 ',
                'id' => 88,
                'last_name' => 'Covarrubias',
                'name' => 'Dña Ana Isabel Varela Hijo',
                'sexo' => 'Masculino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            88 => 
            array (
                'ciudad' => 'Oruro',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Plaza Alfaro, 5, 71º 6º',
                'email' => 'gael.rojas@example.com',
                'fecha_de_nacimiento' => '2003-06-07 ',
                'id' => 89,
                'last_name' => 'Vázquez',
                'name' => 'Lic. María Pilar Gaitán Segundo',
                'sexo' => 'Femenino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            89 => 
            array (
                'ciudad' => 'La Paz',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Carrer Benítez, 3, 15º A',
                'email' => 'alicia70@example.com',
                'fecha_de_nacimiento' => '1984-08-29 ',
                'id' => 90,
                'last_name' => 'Valdés',
                'name' => 'Dr. Marco Zaragoza',
                'sexo' => 'Masculino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            90 => 
            array (
                'ciudad' => 'La Paz',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Ruela Helena, 7, 1º',
                'email' => 'patricia.avalos@example.com',
                'fecha_de_nacimiento' => '2004-06-01 ',
                'id' => 91,
                'last_name' => 'Lorente',
                'name' => 'Yaiza Tamayo',
                'sexo' => 'Masculino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            91 => 
            array (
                'ciudad' => 'La Paz',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Carrer Aaron, 66, 0º',
                'email' => 'roque.pedro@example.org',
                'fecha_de_nacimiento' => '1981-01-07 ',
                'id' => 92,
                'last_name' => 'Carvajal',
                'name' => 'Biel Sarabia',
                'sexo' => 'Femenino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            92 => 
            array (
                'ciudad' => 'La Paz',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Avinguda Morán, 7, 62º C',
                'email' => 'roberto53@example.com',
                'fecha_de_nacimiento' => '2004-12-26 ',
                'id' => 93,
                'last_name' => 'Delvalle',
                'name' => 'Arnau Escobar Segundo',
                'sexo' => 'Masculino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            93 => 
            array (
                'ciudad' => 'Santa Cruz',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Carrer Eva, 7, 2º A',
                'email' => 'pol.alejandro@example.org',
                'fecha_de_nacimiento' => '1971-05-30 ',
                'id' => 94,
                'last_name' => 'Ros',
                'name' => 'Héctor Alonzo',
                'sexo' => 'Masculino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            94 => 
            array (
                'ciudad' => 'Oruro',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Paseo María Ángeles, 935, 4º E',
                'email' => 'rcontreras@example.net',
                'fecha_de_nacimiento' => '1997-01-01 ',
                'id' => 95,
                'last_name' => 'Medrano',
                'name' => 'Jaime Loya',
                'sexo' => 'Femenino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            95 => 
            array (
                'ciudad' => 'Oruro',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Praza Rubio, 8, Ático 3º',
                'email' => 'cedillo.david@example.net',
                'fecha_de_nacimiento' => '1992-08-02 ',
                'id' => 96,
                'last_name' => 'Ibarra',
                'name' => 'Lic. Eric Jáquez Tercero',
                'sexo' => 'Femenino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            96 => 
            array (
                'ciudad' => 'La Paz',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Ruela Valle, 936, 2º A',
                'email' => 'aitor.muro@example.net',
                'fecha_de_nacimiento' => '2021-10-23 ',
                'id' => 97,
                'last_name' => 'Pichardo',
                'name' => 'Valeria Perea',
                'sexo' => 'Masculino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            97 => 
            array (
                'ciudad' => 'Santa Cruz',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Calle Mata, 63, 2º C',
                'email' => 'elara@example.net',
                'fecha_de_nacimiento' => '1974-09-25 ',
                'id' => 98,
                'last_name' => 'Delacrúz',
                'name' => 'Izan Díez',
                'sexo' => 'Masculino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            98 => 
            array (
                'ciudad' => 'Santa Cruz',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Camino Armijo, 29, 40º B',
                'email' => 'carmona.ona@example.com',
                'fecha_de_nacimiento' => '1990-11-11 ',
                'id' => 99,
                'last_name' => 'Suárez',
                'name' => 'Sra. Vera Pedraza',
                'sexo' => 'Masculino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            99 => 
            array (
                'ciudad' => 'Oruro',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Avinguda Hugo, 84, Bajo 3º',
                'email' => 'egalvan@example.com',
                'fecha_de_nacimiento' => '1984-01-10 ',
                'id' => 100,
                'last_name' => 'Villalpando',
                'name' => 'Jan Villaseñor',
                'sexo' => 'Femenino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            100 => 
            array (
                'ciudad' => 'Oruro',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Camiño Omar, 475, 4º D',
                'email' => 'franciscojavier.quintanilla@example.com',
                'fecha_de_nacimiento' => '2014-01-16 ',
                'id' => 101,
                'last_name' => 'Herrero',
                'name' => 'Ing. Ismael Ybarra',
                'sexo' => 'Femenino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            101 => 
            array (
                'ciudad' => 'Santa Cruz',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Avinguda Óscar, 2, 9º C',
                'email' => 'melgar.nadia@example.org',
                'fecha_de_nacimiento' => '1988-06-07 ',
                'id' => 102,
                'last_name' => 'Maldonado',
                'name' => 'Aitor Muñiz',
                'sexo' => 'Femenino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            102 => 
            array (
                'ciudad' => 'Santa Cruz',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Calle Véliz, 16, 27º B',
                'email' => 'pol98@example.org',
                'fecha_de_nacimiento' => '1983-02-21 ',
                'id' => 103,
                'last_name' => 'Narváez',
                'name' => 'Aina Ramos',
                'sexo' => 'Femenino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            103 => 
            array (
                'ciudad' => 'Santa Cruz',
                'created_at' => '2023-08-15 01:19:13',
                'deleted_at' => NULL,
                'direccion' => 'Travessera Aguilera, 822, Entre suelo 6º',
                'email' => 'carlos.escudero@example.com',
                'fecha_de_nacimiento' => '2007-04-25 ',
                'id' => 104,
                'last_name' => 'Gaitán',
                'name' => 'Marco Carballo Tercero',
                'sexo' => 'Masculino',
                'updated_at' => '2023-08-15 01:19:13',
            ),
            104 => 
            array (
                'ciudad' => 'La Paz',
                'created_at' => '2023-08-21 00:43:53',
                'deleted_at' => NULL,
                'direccion' => 'La Paz, Landaeta',
                'email' => 'jim@bolivianontech.com',
                'fecha_de_nacimiento' => '12/04/1990',
                'id' => 105,
                'last_name' => 'Requena',
                'name' => 'Jimmy',
                'sexo' => 'Masculino',
                'updated_at' => '2023-08-21 00:43:53',
            ),
        ));
        
        
    }
}